"""English and Hindi chrome and page copy for the public school site."""

from datetime import date

_DEVANAGARI_DIGITS = str.maketrans("0123456789", "०१२३४५६७८९")


def academic_year(lang: str = "en") -> str:
    """Session label: current calendar year–next year's last two digits (e.g. 2026–27)."""
    year = date.today().year
    label = f"{year}–{str(year + 1)[-2:]}"
    if lang == "hi":
        return label.translate(_DEVANAGARI_DIGITS)
    return label


QUOTES = (
    {
        "image": "assets/quotes/vivekananda.webp",
        "cite": {"en": "Swami Vivekananda", "hi": "स्वामी विवेकानंद"},
        "text": {
            "en": "Education is the manifestation of the perfection already in man.",
            "hi": "शिक्षा मनुष्य में पहले से विद्यमान पूर्णता का प्रकाश है।",
        },
    },
    {
        "image": "assets/quotes/kalam.webp",
        "cite": {"en": "A. P. J. Abdul Kalam", "hi": "ए. पी. जे. अब्दुल कलाम"},
        "text": {
            "en": "The purpose of education is to make good human beings with skill and expertise. Enlightened human beings can be created by teachers.",
            "hi": "शिक्षा का उद्देश्य कुशलता और ज्ञान के साथ अच्छे मनुष्य बनाना है। प्रबुद्ध नागरिक शिक्षकों के मार्गदर्शन में गढ़े जाते हैं।",
        },
    },
    {
        "image": "assets/quotes/tagore.webp",
        "cite": {"en": "Rabindranath Tagore", "hi": "रबीन्द्रनाथ ठाकुर"},
        "text": {
            "en": "The highest education is that which does not merely give us information but makes our life in harmony with all existence.",
            "hi": "सबसे ऊँची शिक्षा वह है जो केवल सूचना नहीं देती, बल्कि हमारे जीवन को सम्पूर्ण सृष्टि के साथ सामंजस्य में लाती है।",
        },
    },
    {
        "image": "assets/quotes/gandhi.webp",
        "cite": {"en": "Mahatma Gandhi", "hi": "महात्मा गांधी"},
        "text": {
            "en": "Literacy in itself is no education. Literacy is not the end of education or even the beginning.",
            "hi": "साक्षरता अपने आप में शिक्षा नहीं है। साक्षरता शिक्षा का अंत नहीं है, न ही उसका आरंभ।",
        },
    },
    {
        "image": "assets/quotes/vivekananda.webp",
        "cite": {"en": "Swami Vivekananda", "hi": "स्वामी विवेकानंद"},
        "text": {
            "en": "We want that education by which character is formed, strength of mind is increased, the intellect is expanded, and by which one can stand on one’s own feet.",
            "hi": "हम वह शिक्षा चाहते हैं जिससे चरित्र बने, मन बलवान हो, बुद्धि का विस्तार हो, और मनुष्य अपने पैरों पर खड़ा हो सके।",
        },
    },
    {
        "image": "assets/quotes/kalam.webp",
        "cite": {"en": "A. P. J. Abdul Kalam", "hi": "ए. पी. जे. अब्दुल कलाम"},
        "text": {
            "en": "Learning gives creativity, creativity leads to thinking, thinking provides knowledge, and knowledge makes you great.",
            "hi": "सीखना सृजनशीलता देता है, सृजनशीलता सोच की ओर ले जाती है, सोच ज्ञान देती है, और ज्ञान मनुष्य को महान बनाता है।",
        },
    },
    {
        "image": "assets/quotes/radhakrishnan.webp",
        "cite": {"en": "Dr S. Radhakrishnan", "hi": "डॉ. एस. राधाकृष्णन"},
        "text": {
            "en": "The true teachers are those who help us think for ourselves.",
            "hi": "सच्चे शिक्षक वे हैं जो हमें स्वयं सोचने में सहायता करते हैं।",
        },
    },
    {
        "image": "assets/quotes/vivekananda.webp",
        "cite": {"en": "Swami Vivekananda", "hi": "स्वामी विवेकानंद"},
        "text": {
            "en": "Arise, awake, and stop not till the goal is reached.",
            "hi": "उठो, जागो और लक्ष्य प्राप्त होने तक रुको मत।",
        },
    },
    {
        "image": "assets/quotes/tagore.webp",
        "cite": {"en": "Rabindranath Tagore", "hi": "रबीन्द्रनाथ ठाकुर"},
        "text": {
            "en": "Don’t limit a child to your own learning, for he was born in another time.",
            "hi": "बच्चे को अपनी शिक्षा की सीमा में न बाँधो; वह दूसरे समय में जन्मा है।",
        },
    },
    {
        "image": "assets/quotes/kalam.webp",
        "cite": {"en": "A. P. J. Abdul Kalam", "hi": "ए. पी. जे. अब्दुल कलाम"},
        "text": {
            "en": "Dream, dream, dream. Dreams transform into thoughts and thoughts result in action.",
            "hi": "सपने देखो, सपने देखो, सपने देखो। सपने विचारों में बदलते हैं और विचार कर्म में।",
        },
    },
)

NOTICE_TENSE = {
    "observe": {
        "en": {
            "before": "The school will observe {title} on {date} on campus. Assembly time will be confirmed by the class teacher and the office.",
            "on": "The school is observing {title} on campus today. Confirm assembly time at the office.",
            "after": "The school observed {title} on {date}. For any follow-up, write to the office.",
        },
        "hi": {
            "before": "विद्यालय {date} को परिसर में {title} मनाएगा। सभा का समय कक्षा-शिक्षक और कार्यालय से पुष्टि होगी।",
            "on": "विद्यालय आज परिसर में {title} मना रहा है। सभा का समय कार्यालय से पुष्टि करें।",
            "after": "विद्यालय ने {date} को {title} मनाया। आगे की जानकारी के लिए कार्यालय को लिखें।",
        },
    },
    "closed": {
        "en": {
            "before": "The school will remain closed for {title} on {date}. If the date changes, treat a message from the office as final.",
            "on": "Holiday for {title}. The school is closed today.",
            "after": "The school remained closed for {title} on {date}.",
        },
        "hi": {
            "before": "{date} को {title} के कारण विद्यालय बंद रहेगा। तिथि बदले तो कार्यालय की सूचना अंतिम मानी जाए।",
            "on": "{title} की छुट्टी है। विद्यालय आज बंद है।",
            "after": "{title} के कारण विद्यालय {date} को बंद रहा।",
        },
    },
}

UI = {
    "en": {
        "html_lang": "en",
        "skip": "Skip to main content",
        "lang_label": "हिन्दी",
        "lang_title": "हिन्दी में देखें",
        "open_menu": "Open menu",
        "open_sub": "Show more pages",
        "nav_home": "Home",
        "nav_about": "About",
        "nav_about_school": "Our story",
        "nav_facilities": "Facilities",
        "nav_reach": "How to reach",
        "nav_rules": "Rules and conduct",
        "nav_academics": "Academics",
        "nav_classes": "Learning stages",
        "nav_life": "Campus & student life",
        "nav_admissions": "Admissions",
        "nav_enquire": "Admission enquiry",
        "nav_faq": "FAQ",
        "nav_results": "Results",
        "nav_results_assess": "Assessment & highlights",
        "nav_notices": "Notices",
        "nav_notices_board": "Notice board",
        "nav_notices_archive": "Notice archive",
        "nav_gallery": "Gallery",
        "nav_careers": "Careers",
        "nav_contact": "Contact",
        "brand": "Nootan Public School",
        "place": "Dharhara, Vaishali, Bihar (844117)",
        "footer_quick": "Quick links",
        "footer_school": "School",
        "footer_contact": "Contact",
        "footer_fb": "Nootan Public School",
        "footer_ig": "nps_dharhara_official",
        "footer_fb_aria": "Facebook: Nootan Public School",
        "footer_ig_aria": "Instagram: nps_dharhara_official",
        "map_open": "Open in Maps",
        "map_title": "Nootan Public School, Dharhara on Google Maps",
        "legal": "© Copyright {year} Nootan Public School, Dharhara<br />All Rights Reserved.",
        "crumbs_home": "Home",
        "site_desc": "Nootan Public School, Dharhara — nurturing young minds from Play (Pre-Nursery) through Class 8.",
        "results_desc": "Look up a marksheet by examination, class, section, name, and roll.",
        "banner_about": "Our story",
        "banner_academics": "Learning & growth",
        "banner_admissions": "Join our community",
        "banner_results": "Celebrating Excellence",
        "banner_notices": "Announcements & Updates",
        "banner_gallery": "Moments & memories",
        "banner_careers": "Join our staff",
        "banner_contact": "Get in Touch",
        "banner_life": "Campus & student life",
        "banner_facilities": "Facilities",
        "banner_faq": "Frequently asked questions",
        "banner_reach": "How to reach",
        "banner_rules": "Rules and conduct",
        "crumb_about_school": "Our story",
        "crumb_classes": "Learning stages",
        "crumb_enquire": "Admission enquiry",
        "crumb_from_office": "From the office",
        "crumb_campus": "Campus pictures",
        "crumb_write": "Write to the office",
        "crumb_marksheet": "Look up a marksheet",
        "home_hero_title": "Nurturing Young Minds, Shaping Bright Futures",
        "home_hero_sub": "Welcome to Nootan Public School, Dharhara — where curiosity meets character, and every child is empowered to learn, discover, and grow together.",
        "home_cta_admissions": "Explore Admissions",
        "home_cta_campus": "Discover Our Campus",
        "home_about": "Welcome to Nootan Public School",
        "home_welcome_quote": "Education is not just preparation for life; education is life itself.",
        "home_about_p1": "At Nootan Public School (NPS), we believe every child is born with unique potential and boundless curiosity. Established with a commitment to educational excellence and grounded in strong moral values, our school provides a safe, vibrant, and nurturing environment for students from Play (Pre-Nursery) through Class 8.",
        "home_about_p2": "We don't just teach from textbooks — we foster critical thinking, creativity, emotional intelligence, and mutual respect. Together with our parents and educators, we build a community where every milestone is celebrated and every student thrives.",
        "home_about_more": "Read the full about page",
        "home_pillars_label": "Core Pillars",
        "home_pillars_title": "The NPS Difference",
        "home_pillars_caption": "What it means for your child",
        "home_pillar_1_title": "Holistic Learning",
        "home_pillar_1_text": "Balanced academic rigor blended with sports, arts, and foundational computer literacy.",
        "home_pillar_2_title": "Value-Based Guidance",
        "home_pillar_2_text": "Instilling discipline, empathy, leadership, and cultural respect from the early years.",
        "home_pillar_3_title": "Caring Educators",
        "home_pillar_3_text": "Dedicated teachers who mentor with patience, individualized attention, and warmth.",
        "home_pillar_4_title": "Safe & Inspiring Space",
        "home_pillar_4_text": "A joyful campus designed to encourage curiosity, exploration, and collaborative play.",
        "home_highlights_label": "At a glance",
        "home_highlights_title": "Key Highlights",
        "home_highlight_1_title": "Foundations First",
        "home_highlight_1_text": "Comprehensive education from Play (Pre-Nursery) to Middle School (Class 8).",
        "home_highlight_2_title": "Modern Pedagogy",
        "home_highlight_2_text": "Activity-based learning, interactive audio-visual concepts, and practical exploration.",
        "home_highlight_3_title": "Co-Curriculars & Sports",
        "home_highlight_3_text": "Competitions, Olympiad training, cultural celebrations, and physical fitness.",
        "home_explore": "Explore",
        "home_start": "Where to start",
        "card_academics": "Play (Pre-Nursery) to Class 8, with subjects and examinations at every stage.",
        "card_results": "Open a marksheet by examination, class, section, name, and roll.",
        "card_admissions": "Enquire by email or visit the office. Fees are not taken on this website.",
        "card_contact": "Write to npsd1970@gmail.com for circulars and admissions.",
        "card_facilities": "Classrooms, playground, and computer from Advanced Sapling.",
        "card_life": "Assembly, Hindi and English, sport, and art as part of the school day.",
        "card_notices": "Read circulars from the office — holidays, meetings, and session dates.",
        "home_campus": "Campus and school day",
        "home_campus_p1": "Teaching takes place in classrooms on the Dharhara campus, with open ground for play. Computer is on the timetable from Advanced Sapling. Art sits beside books in the younger classes; from Class 6, science, social studies, and Sanskrit join the list.",
        "home_campus_p2": "A typical day begins with assembly, then lessons, then time outdoors. Sport is part of education — fitness, fair play, and showing up. For a specific facility for your child, write to the office.",
        "home_notices_label": "Notices",
        "home_notices_title": "From the office",
        "home_notices_note": "Read circulars issued by the office. Open a notice for the full text. See all on the {link}.",
        "home_notices_link": "notices page",
        "home_help": "How can we help?",
        "home_help_p": "For admission, a circular, or a visit to the office, write to the school email. Fees are not collected on this website.",
        "home_help_cta": "Enquire for admission",
        "home_help_mail": "Write to npsd1970@gmail.com",
        "no_notices": "No circulars are listed at present. Write to npsd1970@gmail.com to join the office mailing list.",
        "all_notices": "All notices",
        "notice_circular": "Office circular",
        "about_who": "Shaping Minds, Building Character",
        "about_who_p1": "Founded in 2019 in Dharhara, Vaishali, Nootan Public School was built on a simple yet profound vision: to bring quality, progressive, and value-rich education to our local community. Over the years, NPS has blossomed into a trusted center of learning where young minds find their voice, build their confidence, and develop a lifelong love for learning.",
        "about_who_p2": "Our educational philosophy centers on nurturing the whole child — blending academic rigor with moral grounding, emotional resilience, and creative expression. We view education not merely as classroom instruction, but as a shared journey between teachers, students, and parents working hand-in-hand to help every young learner thrive.",
        "about_desk": "Message from the Desk of the Leadership",
        "about_desk_quote": "At Nootan Public School, we see education as a collaborative journey. When school and family work hand in hand, children flourish. Our commitment is to ensure that your child is recognized, valued, and encouraged to be the best version of themselves every single day. We welcome you to be a part of our growing family.",
        "about_aim": "Vision & Mission",
        "about_vision_label": "Our Vision",
        "about_vision": "To be a community beacon of learning where students develop into curious, confident, and compassionate global citizens guided by moral integrity.",
        "about_mission_label": "Our Mission",
        "about_mission_1": "Cultivate an inclusive, joyful, and supportive environment where every child feels valued.",
        "about_mission_2": "Bridge foundational concepts with practical understanding, digital literacy, and experiential learning.",
        "about_mission_3": "Instill core values of respect, discipline, empathy, and active community participation.",
        "about_values": "Core Values: Growing Together",
        "about_values_caption": "Our commitment",
        "about_value_1_title": "Excellence with Empathy",
        "about_value_1_text": "Encouraging high academic standards while cultivating kindness and mutual respect.",
        "about_value_2_title": "Integrity & Discipline",
        "about_value_2_text": "Building strong ethical foundations, accountability, and positive habits from an early age.",
        "about_value_3_title": "Curiosity & Innovation",
        "about_value_3_text": "Inspiring inquiry, critical thinking, and hands-on discovery across every subject.",
        "about_value_4_title": "Inclusive Community",
        "about_value_4_text": "Partnering closely with parents and educators to support every student's growth path.",
        "about_web": "Explore more",
        "acad_early": "Early Childhood Education: The Foundational Years",
        "acad_early_p": "Our early learning stages mirror nature’s growth journey—from first roots in Play, then a curious seed into a confident, thriving learner:",
        "acad_play_title": "Play (Pre-Nursery) — Taking Root",
        "acad_play_text": "A gentle first school experience through free play, songs, routines, and warm settling-in, so every child feels safe before formal early years begin.",
        "acad_seedling_title": "Seedling (Nursery) — Planting Curiosity",
        "acad_seedling_text": "Focuses on sensory play, habit formation, storytelling, and emotional security for a gentle, joyful transition to school.",
        "acad_sapling_title": "Sapling (LKG) — Branching Out",
        "acad_sapling_text": "Introduces foundational phonics, early numeracy, shape recognition, and creative expression through guided discovery.",
        "acad_adv_title": "Advanced Sapling (UKG) — Ready to Blossom",
        "acad_adv_text": "Builds early reading and writing fluency, basic arithmetic, and self-reliance for a smooth step into Class 1.",
        "acad_primary": "Primary School (Classes 1 to 5)",
        "acad_prim_1_title": "Core Subject Mastery",
        "acad_prim_1_text": "Interactive teaching in Mathematics, Science, Social Studies, English, and Hindi.",
        "acad_prim_2_title": "Experiential Learning",
        "acad_prim_2_text": "Hands-on projects, group activities, and regular quizzes that make concepts memorable.",
        "acad_prim_3_title": "Foundational IT & Digital Skills",
        "acad_prim_3_text": "Early introduction to computer fundamentals, logical thinking, and digital literacy.",
        "acad_middle": "Middle School (Classes 6 to 8)",
        "acad_mid_1_title": "Analytical & Critical Thinking",
        "acad_mid_1_text": "Encouraging analytical problem-solving, science practicals, and structured writing.",
        "acad_mid_2_title": "Olympiad & Competitive Exam Exposure",
        "acad_mid_2_text": "Mentorship for external academic competitions and talent searches to broaden horizons.",
        "acad_mid_3_title": "Leadership & Public Speaking",
        "acad_mid_3_text": "Class presentations, debates, and team projects that prepare students for higher secondary stages.",
        "acad_seat": "Enquire for a seat",
        "life_campus": "On campus",
        "life_1_title": "Smart & Well-Ventilated Classrooms",
        "life_1_text": "Bright, comfortable spaces equipped for interactive learning.",
        "life_2_title": "Computer & Digital Lab",
        "life_2_text": "Hands-on exposure to practical computing to keep students future-ready.",
        "life_3_title": "School Library & Reading Corner",
        "life_3_text": "A curated collection of storybooks, reference guides, and educational magazines that cultivate reading habits.",
        "life_4_title": "Sports & Physical Wellness",
        "life_4_text": "Dedicated playground areas for athletics, team games, yoga, and regular physical education.",
        "life_5_title": "Safety & Care",
        "life_5_text": "Supervised entry, secure boundaries, and a campus-wide culture of kindness and student well-being.",
        "life_uniform": "Uniform and books",
        "life_uniform_p": "The pattern of the uniform and the book list for the year are issued by the office. Ask when you enquire, or write to npsd1970@gmail.com.",
        "life_photo": "Photographs",
        "life_photo_p": "Campus views appear in the gallery. Children’s portraits are published only with the school’s care for privacy, never as a public roll of names.",
        "fac_on": "Our campus",
        "fac_on_p1": "Our campus is thoughtfully designed to provide a safe, well-equipped, and joyful space that fosters academic focus, physical vitality, and creative exploration.",
        "fac_infra": "Key Campus Infrastructure",
        "fac_1_title": "Smart & Well-Ventilated Classrooms",
        "fac_1_text": "Spacious, sunlit classrooms designed for interactive teaching, collaborative group work, and focused individual learning.",
        "fac_2_title": "Computer & Digital Learning Lab",
        "fac_2_text": "Dedicated computer systems to ensure early digital literacy, basic coding concepts, and technological confidence for middle-school learners.",
        "fac_3_title": "Curated Library & Reading Zone",
        "fac_3_text": "A rich collection of storybooks, reference encyclopedias, and educational journals to instill a lifelong habit of reading.",
        "fac_4_title": "Playground & Sports Arena",
        "fac_4_text": "Open play spaces for team sports, athletic training, daily physical exercise, and yoga sessions that promote physical fitness and teamwork.",
        "fac_5_title": "Clean & Safe Drinking Water",
        "fac_5_text": "Modern filtration systems installed across the premises providing clean, safe drinking water for all students and staff.",
        "fac_6_title": "Campus Safety & Cleanliness",
        "fac_6_text": "Secure entry points, continuous staff supervision, clean washrooms, and strict sanitation standards maintained daily.",
        "fac_more": "Need more detail?",
        "ask_office": "Ask the office",
        "adm_overview": "Admissions Overview",
        "adm_welcome": "We welcome new families to join our nurturing learning community. Our admission process is transparent, straightforward, and supportive.",
        "adm_elig_label": "Eligibility",
        "adm_elig": "Admissions are open from Play (Pre-Nursery) up to Class 8.",
        "adm_process": "Process",
        "adm_form_link": "online inquiry form",
        "adm_step1": "Submit the {form_link} or visit the school office.",
        "adm_step2": "Attend a short, friendly interaction and campus walkthrough.",
        "adm_step3": "Complete document verification (Birth Certificate, previous report cards/TC where applicable, and photographs).",
        "adm_enquire": "Take the First Step Toward Your Child’s Bright Future",
        "adm_enquire_p": "Fill out the form below, and our admissions team will connect with you to guide you through the process and arrange a campus visit.",
        "adm_faq": "Frequently asked questions",
        "faq_q": "Frequently asked questions",
        "faq_q1": "What is the age criteria for Early Childhood admissions?",
        "faq_a1": """<ul>
              <li><strong>Play (Pre-Nursery):</strong> 2+ years as of the beginning of the academic session.</li>
              <li><strong>Seedling (Nursery):</strong> 3+ years as of the beginning of the academic session.</li>
              <li><strong>Sapling (LKG):</strong> 4+ years.</li>
              <li><strong>Advanced Sapling (UKG):</strong> 5+ years.</li>
            </ul>""",
        "faq_q2": "What documents are required for admission?",
        "faq_a2": """<ul>
              <li>Child’s official Birth Certificate (photocopy).</li>
              <li>Passport-sized photographs of the child and parents.</li>
              <li>Aadhaar Card copies (child and parents).</li>
              <li>Transfer Certificate (TC) and previous grade report card (for Class 2 and above).</li>
            </ul>""",
        "faq_q3": "Does the school provide transport facilities?",
        "faq_a3": "<p>Yes, safe and supervised local transport services are available connecting nearby localities across Dharhara and surrounding areas.</p>",
        "faq_q4": "What is the school’s academic schedule?",
        "faq_a4": "<p>The school operates from Monday to Saturday, typically running from 8:00 AM to 1:30 PM (timings vary slightly according to seasonal guidelines and early childhood schedules).</p>",
        "faq_q5": "How does NPS ensure individual attention for every child?",
        "faq_a5": "<p>We maintain healthy, low student-teacher ratios to ensure each student receives individualized mentoring, care, and active encouragement in every class.</p>",
        "notices_from": "Announcements & Updates",
        "notices_p": "Stay updated with official communications, holiday schedules, examination notices, and upcoming campus events at NPS.",
        "notices_latest": "Latest Circulars & Updates",
        "notices_latest_1_title": "Academic & Examinations",
        "notices_latest_1_text": "Detailed schedules for term assessments, unit tests, and syllabus guidelines are published well in advance of every exam cycle.",
        "notices_latest_2_title": "School Events & Celebrations",
        "notices_latest_2_text": "Circulars regarding annual functions, sports days, cultural festivals, and National Day celebrations.",
        "notices_latest_3_title": "Parent-Teacher Meetings (PTM)",
        "notices_latest_3_text": "Official intimations for periodic progress reviews and parent-teacher consultations.",
        "notices_latest_4_title": "Holiday & Seasonal Advisories",
        "notices_latest_4_text": "Timely updates regarding seasonal timing adjustments, summer/winter breaks, and administrative notices.",
        "notices_board": "Recent Notices Board",
        "notices_archive": "Official Notice Archive & Filter",
        "notices_archive_p": "Find a circular by class, category, or keyword. Open a row to read the full notice issued by the office.",
        "notices_col_status": "Status",
        "notices_col_category": "Category",
        "notices_col_title": "Notification Title",
        "notices_col_action": "Download / Action",
        "notices_status_active": "Active",
        "notices_view": "View Circular",
        "notices_filter_class": "Filter by Class",
        "notices_filter_category": "Filter by Category",
        "notices_filter_search": "Search",
        "notices_filter_search_ph": "Search notice by keyword...",
        "notices_filter_all": "All",
        "notices_class_18": "Class 1 to 8",
        "notices_cat_academic": "Academic",
        "notices_cat_holidays": "Holidays",
        "notices_cat_events": "Events",
        "notices_cat_administrative": "Administrative",
        "notices_none_filter": "No notices match these filters. Clear the search or choose All to see the full board.",
        "notices_urgent_label": "Important Note for Parents",
        "notices_urgent": "For urgent updates or emergency school advisories (such as weather-related schedule changes), intimations are also sent directly via official SMS and WhatsApp broadcast channels.",
        "gal_h": "Campus pictures",
        "gal_p": "The gallery presents the Dharhara campus — classrooms, grounds, and gathering spaces. Open a section to see photographs issued by the school. Children’s names are not published under a photograph.",
        "gal_1": "Classrooms",
        "gal_2": "Playground",
        "gal_3": "Assembly",
        "gal_4": "Campus",
        "gal_5": "Activities",
        "gal_6": "Office",
        "gal_empty": "Photographs for this album will appear here.",
        "gal_view": "View photographs",
        "gal_albums": "Albums",
        "gal_all": "All albums",
        "reach_place": "Campus Location & Address",
        "reach_p": "Nootan Public School is centrally situated and easily accessible from surrounding localities in Vaishali district.",
        "reach_name_l": "School Name",
        "reach_name": "Nootan Public School",
        "reach_address_l": "Address",
        "reach_address": "Dharhara, District Vaishali, Bihar – 844117",
        "reach_landmark_l": "Landmark",
        "reach_landmark": "Centrally located in Dharhara with clear approach roads suitable for school vans, personal vehicles, and public transport.",
        "reach_visit": "Visiting Hours & Directions",
        "reach_hours_title": "Office & Visitor Hours",
        "reach_hours_text": "Monday – Saturday: 8:00 AM – 3:00 PM (Closed on Sundays and Public Holidays)",
        "reach_public_title": "By Public Transport / Auto-Rickshaw",
        "reach_public_text": "Regular local auto-rickshaws, e-rickshaws, and bus services connect major junction points in Vaishali directly to the Dharhara stop.",
        "reach_car_title": "By Private Vehicle",
        "reach_car_text": "Accessible via local link roads with dedicated parking and safe student drop-off/pick-up zones near the school gate.",
        "reach_tour_title": "Campus Tour Inquiries",
        "reach_tour_text": "Parents wishing to schedule a guided walkthrough can connect with our front desk prior to visiting.",
        "reach_follow": "Write or follow",
        "rules_in": "General Code of Conduct",
        "rules_in_p": "At NPS, discipline is rooted in respect, consistency, and encouragement. Our code of conduct ensures a harmonious, secure, and productive atmosphere for every student.",
        "rules_1_title": "Punctuality & Attendance",
        "rules_1_text": "Students are expected to arrive at school before the morning assembly bell. A minimum of 75% attendance is required to ensure academic continuity.",
        "rules_2_title": "School Uniform & Grooming",
        "rules_2_text": "Students must wear the prescribed, clean, and neatly pressed school uniform on all working days, along with polished shoes and their official ID card.",
        "rules_3_title": "Classroom Courtesy & Respect",
        "rules_3_text": "We practice a culture of mutual respect. Courteous behavior toward teachers, staff members, and fellow classmates is mandatory at all times.",
        "rules_4_title": "Care of School Property",
        "rules_4_text": "Desks, computers, library books, and sports equipment must be handled with care. Any intentional damage will require repair or replacement by the parent/guardian.",
        "rules_5_title": "Leave & Absence Policy",
        "rules_5_text": "All planned leaves must be submitted via written application signed by a parent. In cases of illness, an intimation must be provided on the first day of absence.",
        "rules_6_title": "Zero Tolerance for Bullying",
        "rules_6_text": "NPS maintains a strict anti-bullying and inclusive campus policy. Verbal, physical, or social exclusion of any kind is strictly prohibited and addressed immediately.",
        "contact_intro": "We are always here to support your child’s educational journey. Whether you have questions regarding admissions, academics, or campus visits, please reach out to our administrative team.",
        "contact_place": "Campus Location & Address",
        "contact_inst_l": "Institution",
        "contact_inst": "Nootan Public School",
        "contact_address_l": "Address",
        "contact_address": "Dharhara, District Vaishali, Bihar – 844117",
        "contact_desk_l": "Front Desk",
        "contact_desk": "Available during official school hours for in-person queries and campus tours.",
        "contact_touch": "Get in Touch",
        "contact_email_inq": "Email Inquiries",
        "contact_social_l": "Official Social Channels",
        "contact_social_p": "Follow us on Facebook and Instagram (@nps_dharhara_official) for real-time announcements, celebrations, and campus life updates.",
        "contact_hours": "Office & Visiting Hours",
        "contact_hours_day": "Day",
        "contact_hours_time": "Visiting Hours",
        "contact_hours_svc": "Services Available",
        "contact_hours_week": "Monday – Saturday",
        "contact_hours_week_t": "8:00 AM – 3:00 PM",
        "contact_hours_week_s": "Admissions, document submission, fee desk, general inquiries",
        "contact_hours_sun": "Sunday & Public Holidays",
        "contact_hours_closed": "Closed",
        "contact_write": "Write from this page",
        "contact_write_p": "Fill in the same questions as the school inquiry form. Submit sends your answers to the office. Nothing is stored on this website.",
        "form_student_group": "Student details",
        "form_parent_group": "Parent / Guardian details",
        "form_message_group": "Message / Queries",
        "form_student": "Full name of student",
        "form_child": "Full name of child",
        "form_age": "Date of birth / Age",
        "form_guardian": "Parent / Guardian name",
        "form_address": "Residential address / Locality",
        "form_father": "Father’s name",
        "form_mother": "Mother’s name",
        "form_phone": "Contact number (WhatsApp preferred)",
        "form_email": "Email address",
        "form_grade": "Grade applying for",
        "form_inquiry": "Inquiry type",
        "form_choose": "Choose…",
        "form_query": "Please detail your query",
        "form_query_enquiry": "Any specific questions or notes for the admissions counselor",
        "form_submit": "Submit",
        "form_submit_enquiry": "Submit Enquiry",
        "form_thanks": "Thank you. The office has received your message.",
        "form_required_meaning": "mandatory",
        "form_required_abbr": "Mandatory",
        "form_grade_pre": "Play (Pre-Nursery)",
        "form_grade_seedling": "Seedling (Nursery)",
        "form_grade_sapling": "Sapling (LKG)",
        "form_grade_adv": "Advance Sapling (UKG)",
        "form_grade_1": "Class 1",
        "form_grade_2": "Class 2",
        "form_grade_3": "Class 3",
        "form_grade_4": "Class 4",
        "form_grade_5": "Class 5",
        "form_grade_6": "Class 6",
        "form_grade_7": "Class 7",
        "form_grade_8": "Class 8",
        "form_inq_adm": "Admission process",
        "form_inq_fee": "Fee structure",
        "form_inq_exam": "Exam schedule",
        "form_inq_other": "Other",
        "careers_h": "Careers at Nootan Public School",
        "careers_intro": "Join a passionate community of educators and mentors dedicated to shaping young minds. At Nootan Public School, we believe that inspired teachers inspire students.",
        "careers_intro_2": "We provide a supportive, collaborative, and growth-oriented environment where your teaching craft is valued and encouraged.",
        "careers_why": "Why Teach at NPS?",
        "careers_why_1_title": "Collaborative Culture",
        "careers_why_1_text": "Work alongside caring educators who share ideas, lesson plans, and teaching strategies.",
        "careers_why_2_title": "Professional Growth",
        "careers_why_2_text": "Regular workshops, pedagogical training, and opportunities to lead student initiatives and Olympiad mentoring.",
        "careers_why_3_title": "Modern Resources",
        "careers_why_3_text": "Access to digital learning tools, computer labs, and activity-based teaching aids.",
        "careers_why_4_title": "Supportive Community",
        "careers_why_4_text": "A warm, respectful atmosphere where staff well-being and contributions are celebrated.",
        "careers_open": "Current Openings",
        "careers_col_role": "Position / Role",
        "careers_col_level": "Level / Department",
        "careers_col_req": "Key Requirements",
        "careers_job_1_role": "Early Childhood Educators",
        "careers_job_1_level": "Play (Pre-Nursery), Seedling (Nursery), Sapling (LKG), Advanced Sapling (UKG)",
        "careers_job_1_req": "NTT / Early Childhood Certification / D.El.Ed, patience, and a passion for activity-based teaching.",
        "careers_job_2_role": "Primary Teachers (PRT)",
        "careers_job_2_level": "Classes 1–5 (English, Mathematics, EVS, Hindi)",
        "careers_job_2_req": "Graduate with D.El.Ed / B.Ed, strong communication skills, and concept-driven pedagogy.",
        "careers_job_3_role": "Middle School Teachers (TGT)",
        "careers_job_3_level": "Classes 6–8 (Science, Mathematics, Social Science, English)",
        "careers_job_3_req": "Post-Graduate / Graduate with B.Ed, strong subject mastery, and an interactive teaching approach.",
        "careers_job_4_role": "Computer / IT Instructor",
        "careers_job_4_level": "Play (Pre-Nursery) to Class 8",
        "careers_job_4_req": "BCA / B.Sc (IT/CS) or equivalent, with practical knowledge of foundational computing and digital tools.",
        "careers_job_5_role": "Physical Education & Activity Coach",
        "careers_job_5_level": "Campus-wide",
        "careers_job_5_req": "B.P.Ed / D.P.Ed, with experience coaching sports, yoga, and student fitness routines.",
        "careers_process": "Application Process",
        "careers_step1_title": "Submit your application",
        "careers_step1": "Send an updated résumé or CV with a brief cover letter highlighting your teaching philosophy, or complete the form below.",
        "careers_step2_title": "Initial interaction & discussion",
        "careers_step2": "Shortlisted candidates are invited for a personal or virtual interview to discuss subject expertise and pedagogical approach.",
        "careers_step3_title": "Demo class & final onboarding",
        "careers_step3": "Conduct a short demo classroom session with students or a panel, followed by formal appointment and orientation.",
        "careers_email_p": "Email applications: send your résumé to {mail} with the subject line “Application for [Position Name] – [Your Name]”.",
        "careers_form_p": "Or use the form below. Submit sends your application to the office. A résumé may be emailed, or added as a link in the last field.",
        "careers_pool": "Even if a specific opening is not listed, we welcome résumés from passionate educators for our talent pool for future academic sessions.",
        "careers_apply": "Direct Application Form",
        "careers_name": "Full name",
        "careers_address": "Place / address",
        "careers_age": "Age",
        "careers_gender": "Gender",
        "careers_qual": "Highest education qualification",
        "careers_workplace": "Last workplace",
        "careers_salary": "Expected salary (monthly)",
        "careers_subjects": "Subjects you can teach",
        "careers_subject_other": "Other subject (if any)",
        "careers_classes": "Classes you are qualified to teach",
        "careers_sample": "Link to a résumé, sample lesson plan, or teaching video",
        "careers_submit": "Submit Application",
        "careers_thanks": "Thank you. The office has received your application.",
        "form_gender_male": "Male",
        "form_gender_female": "Female",
        "form_gender_other": "Other",
        "form_qual_bed": "Bachelor of Education (B.Ed)",
        "form_qual_med": "Master of Education (M.Ed)",
        "form_qual_pg": "Post Graduate (PG)",
        "form_qual_ug": "Graduate (UG)",
        "form_qual_other": "Other",
        "form_sub_math": "Mathematics",
        "form_sub_sci": "Science",
        "form_sub_eng": "English",
        "form_sub_hin": "Hindi",
        "form_sub_sst": "Social Studies",
        "form_sub_comp": "Computer",
        "form_sub_art": "Arts and Physical Education",
        "form_sub_evs": "EVS",
        "form_cls_pre": "Pre-Primary (Play–KG)",
        "form_cls_pri": "Primary (1–5)",
        "form_cls_mid": "Middle School (6–8)",
        "crumb_apply": "Apply to teach",
        "results_intro": "At NPS, academic assessment is not just about marks—it is a celebration of continuous progress, conceptual clarity, and individual potential.",
        "results_eval": "Our Evaluation Framework",
        "results_eval_1_title": "Continuous & Comprehensive Assessment",
        "results_eval_1_text": "Regular formative class checks, periodic assessments, and term-end evaluations designed to track concept mastery without exam anxiety.",
        "results_eval_2_title": "Skill & Activity-Based Scoring",
        "results_eval_2_text": "Assessing practical application, oral fluency, project work, and creative problem-solving alongside written tests.",
        "results_eval_3_title": "Regular Parent-Teacher Progress Meets",
        "results_eval_3_text": "Transparent academic review sessions to discuss each child's personal milestones and learning strategies.",
        "results_ach": "Student Achievements & Highlights",
        "results_ach_1_title": "100% Foundational Transition",
        "results_ach_1_text": "Consistent milestone achievement across early childhood stages (Play, Seedling, Sapling, and Advanced Sapling) into primary grades.",
        "results_ach_2_title": "Competitive Olympiads & Contests",
        "results_ach_2_text": "Active student participation and recognition in regional talent exams, science challenges, and national Olympiad platforms.",
        "results_ach_3_title": "Co-Curricular Excellence",
        "results_ach_3_text": "Inter-school awards in debate, arts, sports, and cultural presentations.",
        "results_see": "See your results",
        "results_p1": "Marks are looked up in the school results app. Guardians enter the child’s details and open the marksheet.",
        "results_p2": "You will need the <strong>examination</strong> (1st Term, 2nd Term, Half Yearly, 3rd Term, or Annual), <strong>class</strong>, <strong>section</strong>, <strong>student name</strong>, and <strong>roll</strong>.",
        "results_cta": "See your results",
        "results_p3": "If the lookup does not match, write to the office at {mail} with the child’s name and class.",
        "toppers": "Toppers",
        "toppers_p": "After each examination the school honours class-wise distinction — a portrait and a short word, shared with the family’s consent.",
        "topper_photo": "Portrait",
        "topper_said": "In their words",
        "class_play": "Play (Pre-Nursery)",
        "class_seedling": "Seedling",
        "class_sapling": "Sapling",
        "class_adv": "Advanced Sapling",
        "class_1": "Class 1",
        "class_2": "Class 2",
        "class_3": "Class 3",
        "class_4": "Class 4",
        "class_5": "Class 5",
        "class_6": "Class 6",
        "class_7": "Class 7",
        "class_8": "Class 8",
        "class_1_5": "Class 1–5",
        "class_6_8": "Class 6–8",
        "subj_early": "English, Hindi, Maths, EVS, Art",
        "subj_adv": "English, Hindi, Maths, EVS, Computer",
        "subj_15": "English, Hindi, Maths, EVS, Art, Computer",
        "subj_68": "English, Hindi, Maths, Science, Social Studies, Sanskrit, Computer",
        "mail_subject_adm": "Admission enquiry — NPS Dharhara",
        "mail_subject_form": "School enquiry — Nootan Public School, Dharhara",
        "fb_name": "Nootan Public School",
        "title_home": "Nootan Public School, Dharhara",
        "title_about": "About · Nootan Public School, Dharhara",
        "title_academics": "Academics · Nootan Public School, Dharhara",
        "title_life": "Campus & student life · Nootan Public School, Dharhara",
        "title_facilities": "Facilities · Nootan Public School, Dharhara",
        "title_admissions": "Admissions · Nootan Public School, Dharhara",
        "title_results": "Results · Nootan Public School, Dharhara",
        "title_faq": "FAQ · Nootan Public School, Dharhara",
        "title_notices": "Notices · Nootan Public School, Dharhara",
        "title_notices_archive": "Notice archive · Nootan Public School, Dharhara",
        "title_gallery": "Gallery · Nootan Public School, Dharhara",
        "title_careers": "Careers · Nootan Public School, Dharhara",
        "title_reach": "How to reach · Nootan Public School, Dharhara",
        "title_rules": "Rules · Nootan Public School, Dharhara",
        "title_contact": "Contact · Nootan Public School, Dharhara",
        "og_about": "About · NPS Dharhara",
        "og_academics": "Academics · NPS Dharhara",
        "og_life": "Campus & student life · NPS Dharhara",
        "og_facilities": "Facilities · NPS Dharhara",
        "og_admissions": "Admissions · NPS Dharhara",
        "og_results": "Results · NPS Dharhara",
        "og_faq": "FAQ · NPS Dharhara",
        "og_notices": "Notices · NPS Dharhara",
        "og_gallery": "Gallery · NPS Dharhara",
        "og_careers": "Careers · NPS Dharhara",
        "og_reach": "How to reach · NPS Dharhara",
        "og_rules": "Rules · NPS Dharhara",
        "og_contact": "Contact · NPS Dharhara",
        "og_notice_fallback": "Office circular, Nootan Public School, Dharhara.",
    },
    "hi": {
        "html_lang": "hi",
        "skip": "मुख्य विषय पर जाएँ",
        "lang_label": "अंग्रेज़ी",
        "lang_title": "अंग्रेज़ी में देखें",
        "open_menu": "मेनू खोलें",
        "open_sub": "और पृष्ठ दिखाएँ",
        "nav_home": "मुखपृष्ठ",
        "nav_about": "परिचय",
        "nav_about_school": "हमारी कहानी",
        "nav_facilities": "सुविधाएँ",
        "nav_reach": "कैसे पहुँचें",
        "nav_rules": "नियम और आचरण",
        "nav_academics": "शिक्षा",
        "nav_classes": "सीखने के चरण",
        "nav_life": "परिसर और विद्यार्थी जीवन",
        "nav_admissions": "प्रवेश",
        "nav_enquire": "प्रवेश पूछताछ",
        "nav_faq": "प्रश्नोत्तर",
        "nav_results": "परिणाम",
        "nav_results_assess": "मूल्यांकन और उपलब्धियाँ",
        "nav_notices": "सूचनाएँ",
        "nav_notices_board": "सूचना पट्ट",
        "nav_notices_archive": "सूचना संग्रह",
        "nav_gallery": "गैलरी",
        "nav_careers": "करियर",
        "nav_contact": "संपर्क",
        "brand": "नूतन पब्लिक स्कूल",
        "place": "धरहरा, वैशाली, बिहार (844117)",
        "footer_quick": "त्वरित लिंक",
        "footer_school": "विद्यालय",
        "footer_contact": "संपर्क",
        "footer_fb": "नूतन पब्लिक स्कूल",
        "footer_ig": "nps_dharhara_official",
        "footer_fb_aria": "फेसबुक: नूतन पब्लिक स्कूल",
        "footer_ig_aria": "इंस्टाग्राम: nps_dharhara_official",
        "map_open": "मानचित्र में खोलें",
        "map_title": "नूतन पब्लिक स्कूल, धरहरा — गूगल मैप",
        "legal": "© कॉपीराइट {year} नूतन पब्लिक स्कूल, धरहरा<br />सर्वाधिकार सुरक्षित।",
        "crumbs_home": "मुखपृष्ठ",
        "site_desc": "नूतन पब्लिक स्कूल, धरहरा — प्ले (प्री-नर्सरी) से कक्षा ८ तक युवा मन का पोषण।",
        "results_desc": "परीक्षा, कक्षा, अनुभाग, नाम और रोल से अंकतालिका देखें।",
        "banner_about": "हमारी कहानी",
        "banner_academics": "शिक्षा और विकास",
        "banner_admissions": "हमारे समुदाय से जुड़ें",
        "banner_results": "उत्कृष्टता का सम्मान",
        "banner_notices": "घोषणाएँ और अपडेट",
        "banner_gallery": "पल और स्मृतियाँ",
        "banner_careers": "स्टाफ में शामिल हों",
        "banner_contact": "संपर्क करें",
        "banner_life": "परिसर और विद्यार्थी जीवन",
        "banner_facilities": "सुविधाएँ",
        "banner_faq": "अक्सर पूछे जाने वाले प्रश्न",
        "banner_reach": "कैसे पहुँचें",
        "banner_rules": "नियम और आचरण",
        "crumb_about_school": "हमारी कहानी",
        "crumb_classes": "सीखने के चरण",
        "crumb_enquire": "प्रवेश पूछताछ",
        "crumb_from_office": "कार्यालय से",
        "crumb_campus": "परिसर के चित्र",
        "crumb_write": "कार्यालय को लिखें",
        "crumb_marksheet": "अंकतालिका देखें",
        "home_hero_title": "युवा मन का पोषण, उज्ज्वल भविष्य का निर्माण",
        "home_hero_sub": "नूतन पब्लिक स्कूल, धरहरा में आपका स्वागत है — जहाँ जिज्ञासा चरित्र से मिलती है, और हर बच्चा सीखने, खोजने और साथ बढ़ने का साहस पाता है।",
        "home_cta_admissions": "प्रवेश जानें",
        "home_cta_campus": "परिसर देखें",
        "home_about": "नूतन पब्लिक स्कूल में आपका स्वागत है",
        "home_welcome_quote": "शिक्षा केवल जीवन की तैयारी नहीं है; शिक्षा स्वयं जीवन है।",
        "home_about_p1": "नूतन पब्लिक स्कूल (एनपीएस) में हम मानते हैं कि हर बच्चा अद्वितीय क्षमता और असीम जिज्ञासा लेकर जन्म लेता है। शैक्षिक उत्कृष्टता और सुदृढ़ नैतिक मूल्यों के संकल्प के साथ स्थापित हमारा विद्यालय प्ले (प्री-नर्सरी) से कक्षा ८ तक के विद्यार्थियों के लिए सुरक्षित, जीवंत और पोषक वातावरण देता है।",
        "home_about_p2": "हम केवल पाठ्यपुस्तकों से नहीं पढ़ाते — हम आलोचनात्मक सोच, सृजनशीलता, भावनात्मक बुद्धि और पारस्परिक सम्मान बढ़ाते हैं। अभिभावकों और शिक्षकों के साथ मिलकर हम ऐसा समुदाय बनाते हैं जहाँ हर उपलब्धि मनाई जाती है और हर विद्यार्थी आगे बढ़ता है।",
        "home_about_more": "पूरा परिचय पढ़ें",
        "home_pillars_label": "मूल स्तंभ",
        "home_pillars_title": "एनपीएस की विशेषता",
        "home_pillars_caption": "आपके बच्चे के लिए इसका अर्थ",
        "home_pillar_1_title": "समग्र शिक्षा",
        "home_pillar_1_text": "खेल, कला और आधारभूत कंप्यूटर साक्षरता के साथ संतुलित शैक्षणिक गंभीरता।",
        "home_pillar_2_title": "मूल्य आधारित मार्गदर्शन",
        "home_pillar_2_text": "प्रारंभिक वर्षों से अनुशासन, सहानुभूति, नेतृत्व और सांस्कृतिक सम्मान का बीजारोपण।",
        "home_pillar_3_title": "समर्पित शिक्षक",
        "home_pillar_3_text": "धैर्य, व्यक्तिगत ध्यान और स्नेह के साथ मार्गदर्शन करने वाले शिक्षक।",
        "home_pillar_4_title": "सुरक्षित और प्रेरणादायक परिसर",
        "home_pillar_4_text": "जिज्ञासा, अन्वेषण और सहयोगी खेल को प्रोत्साहित करने वाला आनंदित परिसर।",
        "home_highlights_label": "एक दृष्टि में",
        "home_highlights_title": "मुख्य विशेषताएँ",
        "home_highlight_1_title": "नींव पहले",
        "home_highlight_1_text": "प्ले (प्री-नर्सरी) से माध्यमिक विद्यालय (कक्षा ८) तक समग्र शिक्षा।",
        "home_highlight_2_title": "आधुनिक शिक्षण",
        "home_highlight_2_text": "गतिविधि आधारित अधिगम, संवादात्मक दृश्य-श्रव्य अवधारणाएँ, और व्यावहारिक अन्वेषण।",
        "home_highlight_3_title": "सह-पाठ्यक्रम और खेल",
        "home_highlight_3_text": "प्रतियोगिताएँ, ओलंपियाड प्रशिक्षण, सांस्कृतिक उत्सव और शारीरिक स्वास्थ्य।",
        "home_explore": "जानें",
        "home_start": "यहाँ से शुरू करें",
        "card_academics": "प्ले (प्री-नर्सरी) से कक्षा ८ तक, प्रत्येक स्तर पर विषय और परीक्षाएँ।",
        "card_results": "परीक्षा, कक्षा, अनुभाग, नाम और रोल से अंकतालिका खोलें।",
        "card_admissions": "ईमेल या कार्यालय आकर पूछताछ करें। इस वेबसाइट पर शुल्क नहीं लिया जाता।",
        "card_contact": "परिपत्र और प्रवेश के लिए npsd1970@gmail.com पर लिखें।",
        "card_facilities": "कक्षाएँ, खेल मैदान, और एडवांस्ड सैपलिंग से कंप्यूटर।",
        "card_life": "प्रार्थना सभा, हिंदी और अंग्रेज़ी, खेल और कला — विद्यालय के दिन का हिस्सा।",
        "card_notices": "कार्यालय के परिपत्र पढ़ें — अवकाश, बैठकें और सत्र तिथियाँ।",
        "home_campus": "परिसर और विद्यालय दिवस",
        "home_campus_p1": "पढ़ाई धरहरा परिसर की कक्षाओं में होती है, खेल के लिए खुला मैदान है। एडवांस्ड सैपलिंग से कंप्यूटर समयसारणी में है। छोटी कक्षाओं में कला पुस्तकों के साथ है; कक्षा ६ से विज्ञान, सामाजिक अध्ययन और संस्कृत जुड़ते हैं।",
        "home_campus_p2": "दिन सभा से शुरू होता है, फिर पाठ, फिर बाहर का समय। खेल शिक्षा का भाग है — स्वास्थ्य, निष्पक्ष खेल और उपस्थित रहना। किसी विशेष सुविधा के लिए कार्यालय को लिखें।",
        "home_notices_label": "सूचनाएँ",
        "home_notices_title": "कार्यालय से",
        "home_notices_note": "कार्यालय द्वारा जारी परिपत्र पढ़ें। पूरा पाठ देखने के लिए सूचना खोलें। सभी {link} पर हैं।",
        "home_notices_link": "सूचना पृष्ठ",
        "home_help": "हम कैसे सहायता करें?",
        "home_help_p": "प्रवेश, परिपत्र या कार्यालय आने के लिए विद्यालय ईमेल पर लिखें। इस वेबसाइट पर शुल्क नहीं लिया जाता।",
        "home_help_cta": "प्रवेश पूछताछ",
        "home_help_mail": "npsd1970@gmail.com पर लिखें",
        "no_notices": "इस समय कोई परिपत्र सूचीबद्ध नहीं है। कार्यालय सूची में नाम लिखवाने के लिए npsd1970@gmail.com पर लिखें।",
        "all_notices": "सभी सूचनाएँ",
        "notice_circular": "कार्यालय परिपत्र",
        "about_who": "मन का निर्माण, चरित्र का विकास",
        "about_who_p1": "२०१९ में धरहरा, वैशाली में स्थापित नूतन पब्लिक स्कूल एक सरल किंतु गहरी दृष्टि पर खड़ा है: हमारे स्थानीय समुदाय तक गुणवत्तापूर्ण, प्रगतिशील और मूल्य-समृद्ध शिक्षा पहुँचाना। वर्षों में एनपीएस सीखने का एक विश्वसनीय केंद्र बना है, जहाँ युवा मन अपनी आवाज़ पाते हैं, आत्मविश्वास बनाते हैं, और जीवन भर सीखने का प्रेम विकसित करते हैं।",
        "about_who_p2": "हमारी शैक्षिक दृष्टि पूरे बच्चे का पोषण है — शैक्षणिक गंभीरता को नैतिक आधार, भावनात्मक दृढ़ता और सृजनात्मक अभिव्यक्ति के साथ जोड़ते हुए। हम शिक्षा को केवल कक्षा-शिक्षण नहीं, बल्कि शिक्षकों, विद्यार्थियों और अभिभावकों की साझा यात्रा मानते हैं, ताकि हर युवा शिक्षार्थी आगे बढ़े।",
        "about_desk": "नेतृत्व के कक्ष से संदेश",
        "about_desk_quote": "नूतन पब्लिक स्कूल में हम शिक्षा को एक सहयोगी यात्रा मानते हैं। जब विद्यालय और परिवार साथ चलते हैं, बच्चे फलते-फूलते हैं। हमारी प्रतिबद्धता है कि आपके बच्चे को पहचाना जाए, सम्मान दिया जाए, और प्रत्येक दिन अपने सर्वश्रेष्ठ रूप में बढ़ने के लिए प्रोत्साहित किया जाए। हम आपको अपने बढ़ते परिवार का हिस्सा बनने का स्वागत करते हैं।",
        "about_aim": "दृष्टि और मिशन",
        "about_vision_label": "हमारी दृष्टि",
        "about_vision": "एक ऐसा सामुदायिक ज्ञान-दीप बनना जहाँ विद्यार्थी जिज्ञासु, आत्मविश्वासी और करुणामय वैश्विक नागरिक बनें, जिनका मार्गदर्शन नैतिक सत्यनिष्ठा करे।",
        "about_mission_label": "हमारा मिशन",
        "about_mission_1": "एक समावेशी, आनंदित और सहायक वातावरण गढ़ना जहाँ हर बच्चा सम्मानित महसूस करे।",
        "about_mission_2": "आधारभूत अवधारणाओं को व्यावहारिक समझ, डिजिटल साक्षरता और अनुभव आधारित अधिगम से जोड़ना।",
        "about_mission_3": "सम्मान, अनुशासन, सहानुभूति और सक्रिय सामुदायिक भागीदारी के मूल मूल्य स्थापित करना।",
        "about_values": "मूल मूल्य: साथ बढ़ना",
        "about_values_caption": "हमारी प्रतिबद्धता",
        "about_value_1_title": "सहानुभूति के साथ उत्कृष्टता",
        "about_value_1_text": "उच्च शैक्षणिक मानक प्रोत्साहित करते हुए दया और पारस्परिक सम्मान बढ़ाना।",
        "about_value_2_title": "सत्यनिष्ठा और अनुशासन",
        "about_value_2_text": "प्रारंभिक आयु से सुदृढ़ नैतिक आधार, जवाबदेही और सकारात्मक आदतें बनाना।",
        "about_value_3_title": "जिज्ञासा और नवाचार",
        "about_value_3_text": "हर विषय में पूछताछ, आलोचनात्मक सोच और हाथों से खोज को प्रेरित करना।",
        "about_value_4_title": "समावेशी समुदाय",
        "about_value_4_text": "हर विद्यार्थी के विकास पथ का साथ देने के लिए अभिभावकों और शिक्षकों के साथ निकट सहयोग।",
        "about_web": "और जानें",
        "acad_early": "प्रारंभिक बाल शिक्षा: आधार वर्ष",
        "acad_early_p": "हमारे प्रारंभिक चरण प्रकृति की वृद्धि यात्रा को दर्शाते हैं — प्ले में जड़ें जमाना, फिर जिज्ञासु बीज से आत्मविश्वासी, फलते-फूलते शिक्षार्थी तक:",
        "acad_play_title": "प्ले (प्री-नर्सरी) — जड़ें जमाना",
        "acad_play_text": "मुक्त खेल, गीत, दिनचर्या और स्नेहपूर्ण बसने के साथ पहला विद्यालय अनुभव, ताकि औपचारिक प्रारंभिक वर्ष शुरू होने से पहले हर बच्चा सुरक्षित महसूस करे।",
        "acad_seedling_title": "सीडलिंग (नर्सरी) — जिज्ञासा बोना",
        "acad_seedling_text": "संवेदी खेल, आदत निर्माण, कहानी और भावनात्मक सुरक्षा पर ध्यान, ताकि विद्यालय में प्रवेश मृदु और आनंदित हो।",
        "acad_sapling_title": "सैपलिंग (एलकेजी) — शाखाएँ फैलाना",
        "acad_sapling_text": "निर्देशित खोज के माध्यम से आधारभूत ध्वनि-विज्ञान, प्रारंभिक गणित, आकृति पहचान और सृजनात्मक अभिव्यक्ति।",
        "acad_adv_title": "एडवांस्ड सैपलिंग (यूकेजी) — खिलने को तैयार",
        "acad_adv_text": "प्रारंभिक पठन-लेखन प्रवाह, मूल अंकगणित और आत्मनिर्भरता, ताकि कक्षा १ में कदम सहज हो।",
        "acad_primary": "प्राथमिक विद्यालय (कक्षा १ से ५)",
        "acad_prim_1_title": "मूल विषयों में दक्षता",
        "acad_prim_1_text": "गणित, विज्ञान, सामाजिक अध्ययन, अंग्रेज़ी और हिंदी में संवादात्मक शिक्षण।",
        "acad_prim_2_title": "अनुभव आधारित अधिगम",
        "acad_prim_2_text": "हाथों से परियोजनाएँ, सामूहिक गतिविधियाँ और नियमित प्रश्नोत्तरी, जो अवधारणाओं को यादगार बनाती हैं।",
        "acad_prim_3_title": "आधारभूत आईटी और डिजिटल कौशल",
        "acad_prim_3_text": "कंप्यूटर की मूल बातें, तार्किक सोच और डिजिटल साक्षरता से प्रारंभिक परिचय।",
        "acad_middle": "माध्यमिक विद्यालय (कक्षा ६ से ८)",
        "acad_mid_1_title": "विश्लेषणात्मक और आलोचनात्मक सोच",
        "acad_mid_1_text": "विश्लेषणात्मक समस्या-समाधान, विज्ञान प्रायोगिक कार्य और संरचित लेखन को प्रोत्साहन।",
        "acad_mid_2_title": "ओलंपियाड और प्रतियोगी परीक्षाएँ",
        "acad_mid_2_text": "बाह्य शैक्षणिक प्रतियोगिताओं और प्रतिभा खोज के लिए मार्गदर्शन, ताकि क्षितिज विस्तृत हों।",
        "acad_mid_3_title": "नेतृत्व और सार्वजनिक भाषण",
        "acad_mid_3_text": "कक्षा प्रस्तुतियाँ, वाद-विवाद और टीम परियोजनाएँ, जो उच्च माध्यमिक चरणों के लिए तैयार करती हैं।",
        "acad_seat": "सीट के लिए पूछताछ",
        "life_campus": "परिसर पर",
        "life_1_title": "स्मार्ट और हवादार कक्षाएँ",
        "life_1_text": "संवादात्मक अधिगम के लिए उज्ज्वल, आरामदायक स्थान।",
        "life_2_title": "कंप्यूटर और डिजिटल प्रयोगशाला",
        "life_2_text": "व्यावहारिक कंप्यूटिंग का हाथों से अनुभव, ताकि विद्यार्थी भविष्य के लिए तैयार रहें।",
        "life_3_title": "विद्यालय पुस्तकालय और पठन कोना",
        "life_3_text": "कहानी की पुस्तकें, संदर्भ मार्गदर्शिकाएँ और शैक्षिक पत्रिकाओं का चयन, जो पठन की आदत बढ़ाता है।",
        "life_4_title": "खेल और शारीरिक स्वास्थ्य",
        "life_4_text": "एथलेटिक्स, टीम खेल, योग और नियमित शारीरिक शिक्षा के लिए समर्पित खेल क्षेत्र।",
        "life_5_title": "सुरक्षा और देखभाल",
        "life_5_text": "निगरानीयुक्त प्रवेश, सुरक्षित सीमाएँ, और दया तथा विद्यार्थी कल्याण की परिसर-व्यापी संस्कृति।",
        "life_uniform": "वर्दी और पुस्तकें",
        "life_uniform_p": "वर्दी का स्वरूप और वर्ष की पुस्तक सूची कार्यालय जारी करता है। पूछताछ करते समय पूछें, या npsd1970@gmail.com पर लिखें।",
        "life_photo": "चित्र",
        "life_photo_p": "परिसर के दृश्य गैलरी में हैं। बच्चों के चित्र विद्यालय की गोपनीयता की नीति के साथ ही प्रकाशित होते हैं, सार्वजनिक नाम-सूची के रूप में नहीं।",
        "fac_on": "हमारा परिसर",
        "fac_on_p1": "हमारा परिसर सुरक्षित, सुसज्जित और आनंदित स्थान देने के लिए सोच-समझकर बनाया गया है, जो शैक्षणिक एकाग्रता, शारीरिक ऊर्जा और सृजनात्मक अन्वेषण बढ़ाता है।",
        "fac_infra": "प्रमुख परिसर अवसंरचना",
        "fac_1_title": "स्मार्ट और हवादार कक्षाएँ",
        "fac_1_text": "संवादात्मक शिक्षण, सामूहिक कार्य और केंद्रित व्यक्तिगत अध्ययन के लिए विस्तृत, सूर्य-प्रकाशित कक्षाएँ।",
        "fac_2_title": "कंप्यूटर और डिजिटल अधिगम प्रयोगशाला",
        "fac_2_text": "प्रारंभिक डिजिटल साक्षरता, मूल कोडिंग अवधारणाएँ और माध्यमिक विद्यार्थियों में तकनीकी आत्मविश्वास के लिए समर्पित कंप्यूटर व्यवस्था।",
        "fac_3_title": "पुस्तकालय और पठन क्षेत्र",
        "fac_3_text": "आजीवन पठन की आदत बढ़ाने के लिए कहानी की पुस्तकें, संदर्भ विश्वकोश और शैक्षिक पत्रिकाओं का समृद्ध संग्रह।",
        "fac_4_title": "खेल मैदान और क्रीड़ा क्षेत्र",
        "fac_4_text": "टीम खेल, एथलेटिक प्रशिक्षण, दैनिक व्यायाम और योग के लिए खुले स्थान, जो स्वास्थ्य और सहयोग बढ़ाते हैं।",
        "fac_5_title": "स्वच्छ और सुरक्षित पेयजल",
        "fac_5_text": "परिसर में आधुनिक निस्पंदन व्यवस्था, जो सभी विद्यार्थियों और स्टाफ के लिए स्वच्छ, सुरक्षित पेयजल देती है।",
        "fac_6_title": "परिसर सुरक्षा और स्वच्छता",
        "fac_6_text": "सुरक्षित प्रवेश द्वार, निरंतर स्टाफ निगरानी, स्वच्छ शौचालय, और प्रतिदिन कड़े स्वच्छता मानक।",
        "fac_more": "और विवरण चाहिए?",
        "ask_office": "कार्यालय से पूछें",
        "adm_overview": "प्रवेश परिचय",
        "adm_welcome": "हम नए परिवारों का हमारे पोषणपूर्ण शिक्षण समुदाय में स्वागत करते हैं। हमारी प्रवेश प्रक्रिया पारदर्शी, सरल और सहयोगपूर्ण है।",
        "adm_elig_label": "पात्रता",
        "adm_elig": "प्रवेश प्ले (प्री-नर्सरी) से कक्षा ८ तक खुले हैं।",
        "adm_process": "प्रक्रिया",
        "adm_form_link": "ऑनलाइन पूछताछ फॉर्म",
        "adm_step1": "{form_link} जमा करें, या विद्यालय कार्यालय आएँ।",
        "adm_step2": "एक संक्षिप्त, मैत्रीपूर्ण बातचीत और परिसर भ्रमण में शामिल हों।",
        "adm_step3": "दस्तावेज़ सत्यापन पूरा करें (जन्म प्रमाणपत्र, जहाँ लागू हो पिछले रिपोर्ट कार्ड/टीसी, और फोटो)।",
        "adm_enquire": "अपने बच्चे के उज्ज्वल भविष्य की ओर पहला कदम बढ़ाएँ",
        "adm_enquire_p": "नीचे दिया फॉर्म भरें; हमारी प्रवेश टीम आपसे संपर्क करेगी, प्रक्रिया समझाएगी और परिसर भ्रमण तय करेगी।",
        "adm_faq": "अक्सर पूछे जाने वाले प्रश्न",
        "faq_q": "अक्सर पूछे जाने वाले प्रश्न",
        "faq_q1": "प्रारंभिक बाल्यावस्था प्रवेश के लिए आयु मानदंड क्या है?",
        "faq_a1": """<ul>
              <li><strong>प्ले (प्री-नर्सरी):</strong> शैक्षणिक सत्र के आरंभ में २+ वर्ष।</li>
              <li><strong>सीडलिंग (नर्सरी):</strong> शैक्षणिक सत्र के आरंभ में ३+ वर्ष।</li>
              <li><strong>सैपलिंग (एलकेजी):</strong> ४+ वर्ष।</li>
              <li><strong>एडवांस्ड सैपलिंग (यूकेजी):</strong> ५+ वर्ष।</li>
            </ul>""",
        "faq_q2": "प्रवेश के लिए कौन-से दस्तावेज़ आवश्यक हैं?",
        "faq_a2": """<ul>
              <li>बच्चे का आधिकारिक जन्म प्रमाणपत्र (फोटोकॉपी)।</li>
              <li>बच्चे और अभिभावकों के पासपोर्ट आकार के फोटो।</li>
              <li>आधार कार्ड की प्रतियाँ (बच्चा और अभिभावक)।</li>
              <li>स्थानांतरण प्रमाणपत्र (टीसी) और पिछली कक्षा का रिपोर्ट कार्ड (कक्षा २ और उससे ऊपर)।</li>
            </ul>""",
        "faq_q3": "क्या विद्यालय परिवहन सुविधा देता है?",
        "faq_a3": "<p>हाँ, धरहरा और आस-पास के क्षेत्रों को जोड़ने वाली सुरक्षित और पर्यवेक्षित स्थानीय परिवहन सेवा उपलब्ध है।</p>",
        "faq_q4": "विद्यालय का शैक्षणिक समय क्या है?",
        "faq_a4": "<p>विद्यालय सोमवार से शनिवार तक चलता है, सामान्यतः प्रातः ८:०० से अपराह्न १:३० तक (समय मौसमी दिशानिर्देशों और प्रारंभिक बाल्यावस्था कार्यक्रम के अनुसार थोड़ा बदल सकता है)।</p>",
        "faq_q5": "एनपीएस हर बच्चे पर व्यक्तिगत ध्यान कैसे सुनिश्चित करता है?",
        "faq_a5": "<p>हम स्वस्थ, कम विद्यार्थी-शिक्षक अनुपात बनाए रखते हैं ताकि प्रत्येक विद्यार्थी को हर कक्षा में व्यक्तिगत मार्गदर्शन, देखभाल और सक्रिय प्रोत्साहन मिले।</p>",
        "notices_from": "घोषणाएँ और अपडेट",
        "notices_p": "एनपीएस की आधिकारिक सूचनाएँ, अवकाश कार्यक्रम, परीक्षा सूचनाएँ और आगामी परिसर कार्यक्रम यहाँ देखें।",
        "notices_latest": "नवीनतम परिपत्र और अपडेट",
        "notices_latest_1_title": "शैक्षणिक और परीक्षाएँ",
        "notices_latest_1_text": "सत्र आकलन, इकाई परीक्षाओं और पाठ्यक्रम दिशानिर्देशों का विस्तृत कार्यक्रम हर परीक्षा चक्र से काफी पहले प्रकाशित किया जाता है।",
        "notices_latest_2_title": "विद्यालय कार्यक्रम और उत्सव",
        "notices_latest_2_text": "वार्षिक समारोह, खेल दिवस, सांस्कृतिक उत्सव और राष्ट्रीय पर्वों से जुड़े परिपत्र।",
        "notices_latest_3_title": "अभिभावक-शिक्षक बैठकें (पीटीएम)",
        "notices_latest_3_text": "आवधिक प्रगति समीक्षा और अभिभावक-शिक्षक परामर्श की आधिकारिक सूचना।",
        "notices_latest_4_title": "अवकाश और मौसमी सलाह",
        "notices_latest_4_text": "मौसमी समय-समायोजन, ग्रीष्म/शीत अवकाश और प्रशासनिक सूचनाओं के समय पर अपडेट।",
        "notices_board": "हाल की सूचना पट्ट",
        "notices_archive": "आधिकारिक सूचना संग्रह और फ़िल्टर",
        "notices_archive_p": "कक्षा, श्रेणी या शब्द से परिपत्र खोजें। पूरी सूचना पढ़ने के लिए पंक्ति खोलें।",
        "notices_col_status": "स्थिति",
        "notices_col_category": "श्रेणी",
        "notices_col_title": "सूचना शीर्षक",
        "notices_col_action": "डाउनलोड / कार्रवाई",
        "notices_status_active": "सक्रिय",
        "notices_view": "परिपत्र देखें",
        "notices_filter_class": "कक्षा से फ़िल्टर",
        "notices_filter_category": "श्रेणी से फ़िल्टर",
        "notices_filter_search": "खोज",
        "notices_filter_search_ph": "शब्द से सूचना खोजें…",
        "notices_filter_all": "सभी",
        "notices_class_18": "कक्षा १ से ८",
        "notices_cat_academic": "शैक्षणिक",
        "notices_cat_holidays": "अवकाश",
        "notices_cat_events": "कार्यक्रम",
        "notices_cat_administrative": "प्रशासनिक",
        "notices_none_filter": "इन फ़िल्टर से कोई सूचना नहीं मिली। खोज साफ़ करें या सभी चुनें।",
        "notices_urgent_label": "अभिभावकों के लिए महत्वपूर्ण नोट",
        "notices_urgent": "अत्यावश्यक अपडेट या आपात विद्यालय सलाह (जैसे मौसम से जुड़े समय-परिवर्तन) आधिकारिक एसएमएस और व्हाट्सऐप प्रसार चैनलों पर भी भेजे जाते हैं।",
        "gal_h": "परिसर के चित्र",
        "gal_p": "गैलरी धरहरा परिसर प्रस्तुत करती है — कक्षाएँ, मैदान और सभा स्थल। खंड खोलकर विद्यालय द्वारा जारी चित्र देखें। चित्र के नीचे बच्चों के नाम नहीं छपते।",
        "gal_1": "कक्षाएँ",
        "gal_2": "खेल मैदान",
        "gal_3": "सभा",
        "gal_4": "परिसर",
        "gal_5": "गतिविधियाँ",
        "gal_6": "कार्यालय",
        "gal_empty": "इस एल्बम की तस्वीरें यहाँ दिखेंगी।",
        "gal_view": "चित्र देखें",
        "gal_albums": "एल्बम",
        "gal_all": "सभी एल्बम",
        "reach_place": "परिसर स्थान और पता",
        "reach_p": "नूतन पब्लिक स्कूल केंद्रीय स्थान पर स्थित है और वैशाली जिले के आस-पास के क्षेत्रों से आसानी से पहुँचा जा सकता है।",
        "reach_name_l": "विद्यालय का नाम",
        "reach_name": "नूतन पब्लिक स्कूल",
        "reach_address_l": "पता",
        "reach_address": "धरहरा, जिला वैशाली, बिहार – ८४४११७",
        "reach_landmark_l": "पहचान",
        "reach_landmark": "धरहरा के केंद्र में स्थित, स्पष्ट पहुँच मार्गों के साथ — विद्यालय वैन, निजी वाहन और सार्वजनिक परिवहन के लिए उपयुक्त।",
        "reach_visit": "मुलाकात समय और दिशा-निर्देश",
        "reach_hours_title": "कार्यालय और आगंतुक समय",
        "reach_hours_text": "सोमवार – शनिवार: प्रातः ८:०० – अपराह्न ३:०० (रविवार और सार्वजनिक अवकाश पर बंद)",
        "reach_public_title": "सार्वजनिक परिवहन / ऑटो-रिक्शा से",
        "reach_public_text": "नियमित स्थानीय ऑटो-रिक्शा, ई-रिक्शा और बस सेवाएँ वैशाली के प्रमुख जंक्शनों को धरहरा स्टॉप से जोड़ती हैं।",
        "reach_car_title": "निजी वाहन से",
        "reach_car_text": "स्थानीय संपर्क मार्गों से पहुँच; विद्यालय द्वार के पास समर्पित पार्किंग और सुरक्षित छात्र उतारने–चढ़ाने का क्षेत्र।",
        "reach_tour_title": "परिसर भ्रमण पूछताछ",
        "reach_tour_text": "मार्गदर्शित भ्रमण चाहने वाले अभिभावक आने से पहले फ्रंट डेस्क से संपर्क कर सकते हैं।",
        "reach_follow": "लिखें या अनुसरण करें",
        "rules_in": "सामान्य आचार संहिता",
        "rules_in_p": "एनपीएस में अनुशासन सम्मान, निरंतरता और प्रोत्साहन पर टिका है। हमारी आचार संहिता हर विद्यार्थी के लिए सामंजस्यपूर्ण, सुरक्षित और उत्पादक वातावरण सुनिश्चित करती है।",
        "rules_1_title": "समयबद्धता और उपस्थिति",
        "rules_1_text": "विद्यार्थियों से अपेक्षा है कि वे प्रातः सभा की घंटी से पहले विद्यालय पहुँचें। शैक्षणिक निरंतरता के लिए न्यूनतम ७५% उपस्थिति आवश्यक है।",
        "rules_2_title": "विद्यालय वर्दी और स्वच्छता",
        "rules_2_text": "सभी कार्य दिवसों पर निर्धारित, स्वच्छ और अच्छी तरह इस्त्री की गई विद्यालय वर्दी, पॉलिश किए जूते और आधिकारिक पहचान पत्र अनिवार्य हैं।",
        "rules_3_title": "कक्षा में शिष्टाचार और सम्मान",
        "rules_3_text": "हम पारस्परिक सम्मान की संस्कृति अपनाते हैं। शिक्षकों, स्टाफ और सहपाठियों के प्रति विनम्र व्यवहार हर समय अनिवार्य है।",
        "rules_4_title": "विद्यालय संपत्ति की देखभाल",
        "rules_4_text": "डेस्क, कंप्यूटर, पुस्तकालय की पुस्तकें और खेल सामग्री सावधानी से संभालें। जानबूझकर क्षति पर अभिभावक को मरम्मत या प्रतिस्थापन करना होगा।",
        "rules_5_title": "अवकाश और अनुपस्थिति नीति",
        "rules_5_text": "सभी नियोजित अवकाश अभिभावक द्वारा हस्ताक्षरित लिखित आवेदन से जमा करें। बीमारी की स्थिति में अनुपस्थिति के पहले दिन सूचना देनी होगी।",
        "rules_6_title": "उत्पीड़न के प्रति शून्य सहनशीलता",
        "rules_6_text": "एनपीएस कठोर उत्पीड़न-विरोधी और समावेशी परिसर नीति रखता है। मौखिक, शारीरिक या सामाजिक बहिष्कार पूर्णतः निषिद्ध है और तत्काल संबोधित किया जाता है।",
        "contact_intro": "हम आपके बच्चे की शैक्षिक यात्रा में हमेशा सहयोग के लिए यहाँ हैं। प्रवेश, शिक्षा या परिसर भ्रमण से जुड़े किसी भी प्रश्न के लिए हमारी प्रशासनिक टीम से संपर्क करें।",
        "contact_place": "परिसर स्थान और पता",
        "contact_inst_l": "संस्थान",
        "contact_inst": "नूतन पब्लिक स्कूल",
        "contact_address_l": "पता",
        "contact_address": "धरहरा, जिला वैशाली, बिहार – ८४४११७",
        "contact_desk_l": "फ्रंट डेस्क",
        "contact_desk": "व्यक्तिगत पूछताछ और परिसर भ्रमण के लिए आधिकारिक विद्यालय समय में उपलब्ध।",
        "contact_touch": "संपर्क करें",
        "contact_email_inq": "ईमेल पूछताछ",
        "contact_social_l": "आधिकारिक सोशल चैनल",
        "contact_social_p": "ताज़ा सूचनाओं, उत्सवों और परिसर जीवन के अपडेट के लिए फेसबुक और इंस्टाग्राम (@nps_dharhara_official) पर हमें फ़ॉलो करें।",
        "contact_hours": "कार्यालय और मुलाकात समय",
        "contact_hours_day": "दिन",
        "contact_hours_time": "मुलाकात समय",
        "contact_hours_svc": "उपलब्ध सेवाएँ",
        "contact_hours_week": "सोमवार – शनिवार",
        "contact_hours_week_t": "प्रातः ८:०० – अपराह्न ३:००",
        "contact_hours_week_s": "प्रवेश, दस्तावेज़ जमा करना, शुल्क डेस्क, सामान्य पूछताछ",
        "contact_hours_sun": "रविवार और सार्वजनिक अवकाश",
        "contact_hours_closed": "बंद",
        "contact_write": "इस पृष्ठ से लिखें",
        "contact_write_p": "विद्यालय पूछताछ फॉर्म जैसे ही प्रश्न यहाँ भरें। जमा करने पर उत्तर कार्यालय को जाते हैं। इस वेबसाइट पर कुछ संग्रहीत नहीं होता।",
        "form_student_group": "विद्यार्थी विवरण",
        "form_parent_group": "अभिभावक / संरक्षक विवरण",
        "form_message_group": "संदेश / प्रश्न",
        "form_student": "छात्र का पूरा नाम",
        "form_child": "बच्चे का पूरा नाम",
        "form_age": "जन्म तिथि / आयु",
        "form_guardian": "अभिभावक / संरक्षक का नाम",
        "form_address": "आवासीय पता / मोहल्ला",
        "form_father": "पिता का नाम",
        "form_mother": "माता का नाम",
        "form_phone": "संपर्क संख्या (व्हाट्सऐप बेहतर)",
        "form_email": "ईमेल पता",
        "form_grade": "जिस कक्षा के लिए आवेदन कर रहे हैं",
        "form_inquiry": "पूछताछ का प्रकार",
        "form_choose": "चुनें…",
        "form_query": "अपनी पूछताछ विस्तार से लिखें",
        "form_query_enquiry": "प्रवेश परामर्शदाता के लिए कोई विशेष प्रश्न या नोट",
        "form_submit": "जमा करें",
        "form_submit_enquiry": "पूछताछ जमा करें",
        "form_thanks": "धन्यवाद। कार्यालय को आपका संदेश मिल गया है।",
        "form_required_meaning": "अनिवार्य",
        "form_required_abbr": "अनिवार्य",
        "form_grade_pre": "प्ले (प्री-नर्सरी)",
        "form_grade_seedling": "सीडलिंग (नर्सरी)",
        "form_grade_sapling": "सैपलिंग (एलकेजी)",
        "form_grade_adv": "एडवांस सैपलिंग (यूकेजी)",
        "form_grade_1": "कक्षा १",
        "form_grade_2": "कक्षा २",
        "form_grade_3": "कक्षा ३",
        "form_grade_4": "कक्षा ४",
        "form_grade_5": "कक्षा ५",
        "form_grade_6": "कक्षा ६",
        "form_grade_7": "कक्षा ७",
        "form_grade_8": "कक्षा ८",
        "form_inq_adm": "प्रवेश प्रक्रिया",
        "form_inq_fee": "शुल्क विवरण",
        "form_inq_exam": "परीक्षा कार्यक्रम",
        "form_inq_other": "अन्य",
        "careers_h": "नूतन पब्लिक स्कूल में करियर",
        "careers_intro": "युवा मन को आकार देने के लिए समर्पित शिक्षकों और मार्गदर्शकों के उत्साही समुदाय से जुड़ें। नूतन पब्लिक स्कूल में हम मानते हैं कि प्रेरित शिक्षक विद्यार्थियों को प्रेरित करते हैं।",
        "careers_intro_2": "हम सहायक, सहयोगी और विकासोन्मुख वातावरण देते हैं, जहाँ आपके शिक्षण कौशल को सम्मान और प्रोत्साहन मिलता है।",
        "careers_why": "एनपीएस में क्यों पढ़ाएँ?",
        "careers_why_1_title": "सहयोगी संस्कृति",
        "careers_why_1_text": "ऐसे समर्पित शिक्षकों के साथ काम करें जो विचार, पाठ योजनाएँ और शिक्षण रणनीतियाँ साझा करते हैं।",
        "careers_why_2_title": "व्यावसायिक विकास",
        "careers_why_2_text": "नियमित कार्यशालाएँ, शिक्षण प्रशिक्षण, और विद्यार्थी पहलों व ओलंपियाड मार्गदर्शन का अवसर।",
        "careers_why_3_title": "आधुनिक संसाधन",
        "careers_why_3_text": "डिजिटल अधिगम उपकरण, कंप्यूटर प्रयोगशालाएँ और गतिविधि आधारित शिक्षण सामग्री।",
        "careers_why_4_title": "सहायक समुदाय",
        "careers_why_4_text": "एक गर्मजोशी भरा, सम्मानपूर्ण वातावरण जहाँ स्टाफ की सेहत और योगदान का उत्सव मनाया जाता है।",
        "careers_open": "वर्तमान रिक्तियाँ",
        "careers_col_role": "पद / भूमिका",
        "careers_col_level": "स्तर / विभाग",
        "careers_col_req": "मुख्य अपेक्षाएँ",
        "careers_job_1_role": "प्रारंभिक बाल्यावस्था शिक्षक",
        "careers_job_1_level": "प्ले (प्री-नर्सरी), सीडलिंग (नर्सरी), सैपलिंग (एलकेजी), एडवांस्ड सैपलिंग (यूकेजी)",
        "careers_job_1_req": "एनटीटी / प्रारंभिक बाल्यावस्था प्रमाणपत्र / डी.एल.एड, धैर्य, और गतिविधि आधारित शिक्षण के प्रति उत्साह।",
        "careers_job_2_role": "प्राथमिक शिक्षक (पीआरटी)",
        "careers_job_2_level": "कक्षा १–५ (अंग्रेज़ी, गणित, ईवीएस, हिंदी)",
        "careers_job_2_req": "स्नातक के साथ डी.एल.एड / बी.एड, सुदृढ़ संप्रेषण, और अवधारणा आधारित शिक्षण।",
        "careers_job_3_role": "मिडिल स्कूल शिक्षक (टीजीटी)",
        "careers_job_3_level": "कक्षा ६–८ (विज्ञान, गणित, सामाजिक विज्ञान, अंग्रेज़ी)",
        "careers_job_3_req": "स्नातकोत्तर / स्नातक के साथ बी.एड, विषय में दक्षता, और संवादात्मक शिक्षण दृष्टिकोण।",
        "careers_job_4_role": "कंप्यूटर / आईटी प्रशिक्षक",
        "careers_job_4_level": "प्ले (प्री-नर्सरी) से कक्षा ८",
        "careers_job_4_req": "बीसीए / बी.एससी (आईटी/सीएस) या समकक्ष, आधारभूत कंप्यूटिंग और डिजिटल उपकरणों का व्यावहारिक ज्ञान।",
        "careers_job_5_role": "शारीरिक शिक्षा और गतिविधि कोच",
        "careers_job_5_level": "पूरा परिसर",
        "careers_job_5_req": "बी.पी.एड / डी.पी.एड, खेल, योग और विद्यार्थी फिटनेस दिनचर्या के प्रशिक्षण का अनुभव।",
        "careers_process": "आवेदन प्रक्रिया",
        "careers_step1_title": "आवेदन जमा करें",
        "careers_step1": "अपना अद्यतन बायोडाटा/सीवी और शिक्षण दर्शन बताता संक्षिप्त कवर लेटर भेजें, या नीचे दिया फॉर्म भरें।",
        "careers_step2_title": "प्रारंभिक बातचीत और चर्चा",
        "careers_step2": "चयनित उम्मीदवारों को विषय दक्षता और शिक्षण दृष्टिकोण पर व्यक्तिगत या ऑनलाइन साक्षात्कार के लिए आमंत्रित किया जाता है।",
        "careers_step3_title": "डेमो कक्षा और अंतिम नियुक्ति",
        "careers_step3": "विद्यार्थियों या पैनल के साथ संक्षिप्त डेमो कक्षा, उसके बाद औपचारिक नियुक्ति और ओरिएंटेशन।",
        "careers_email_p": "ईमेल आवेदन: अपना बायोडाटा {mail} पर भेजें, विषय पंक्ति: “Application for [Position Name] – [Your Name]”.",
        "careers_form_p": "अथवा नीचे दिया फॉर्म भरें। जमा करने पर आवेदन कार्यालय को जाता है। बायोडाटा ईमेल से भेज सकते हैं, या अंतिम फ़ील्ड में लिंक जोड़ सकते हैं।",
        "careers_pool": "यदि कोई विशिष्ट रिक्ति सूचीबद्ध न हो, तब भी भावी सत्रों के लिए प्रतिभा पूल में उत्साही शिक्षकों के बायोडाटा आमंत्रित हैं।",
        "careers_apply": "सीधा आवेदन फॉर्म",
        "careers_name": "पूरा नाम",
        "careers_address": "पता",
        "careers_age": "आयु",
        "careers_gender": "लिंग",
        "careers_qual": "उच्चतम शैक्षणिक योग्यता",
        "careers_workplace": "पिछला कार्यस्थल",
        "careers_salary": "अपेक्षित वेतन (मासिक)",
        "careers_subjects": "आप कौन से विषय पढ़ा सकते हैं",
        "careers_subject_other": "अन्य विषय (यदि कोई हो)",
        "careers_classes": "आप किन कक्षाओं को पढ़ाने के लिए योग्य हैं",
        "careers_sample": "बायोडाटा, नमूना पाठ योजना या शिक्षण वीडियो का लिंक",
        "careers_submit": "आवेदन जमा करें",
        "careers_thanks": "धन्यवाद। कार्यालय को आपका आवेदन मिल गया है।",
        "form_gender_male": "पुरुष",
        "form_gender_female": "महिला",
        "form_gender_other": "अन्य",
        "form_qual_bed": "बैचलर ऑफ एजुकेशन (बी.एड.)",
        "form_qual_med": "मास्टर ऑफ एजुकेशन (एम.एड.)",
        "form_qual_pg": "स्नातकोत्तर (पी.जी.)",
        "form_qual_ug": "स्नातक (यू.जी.)",
        "form_qual_other": "अन्य",
        "form_sub_math": "गणित",
        "form_sub_sci": "विज्ञान",
        "form_sub_eng": "अंग्रेज़ी",
        "form_sub_hin": "हिंदी",
        "form_sub_sst": "सामाजिक अध्ययन",
        "form_sub_comp": "कंप्यूटर",
        "form_sub_art": "कला और शारीरिक शिक्षा",
        "form_sub_evs": "ईवीएस",
        "form_cls_pre": "प्री-प्राइमरी (प्ले–केजी)",
        "form_cls_pri": "प्राइमरी (१–५)",
        "form_cls_mid": "मिडिल स्कूल (६–८)",
        "crumb_apply": "शिक्षण आवेदन",
        "results_intro": "एनपीएस में शैक्षणिक मूल्यांकन केवल अंकों तक सीमित नहीं है — यह निरंतर प्रगति, अवधारणात्मक स्पष्टता और व्यक्तिगत क्षमता का उत्सव है।",
        "results_eval": "हमारा मूल्यांकन ढाँचा",
        "results_eval_1_title": "सतत एवं व्यापक मूल्यांकन",
        "results_eval_1_text": "नियमित रचनात्मक कक्षा जाँच, आवधिक आकलन और सत्रांत मूल्यांकन — परीक्षा की चिंता के बिना अवधारणा की पकड़ को मापने के लिए।",
        "results_eval_2_title": "कौशल और गतिविधि आधारित अंक",
        "results_eval_2_text": "लिखित परीक्षा के साथ व्यावहारिक अनुप्रयोग, मौखिक प्रवाह, परियोजना कार्य और रचनात्मक समस्या-समाधान का आकलन।",
        "results_eval_3_title": "नियमित अभिभावक-शिक्षक प्रगति बैठकें",
        "results_eval_3_text": "प्रत्येक बच्चे के व्यक्तिगत पड़ाव और सीखने की रणनीतियों पर पारदर्शी शैक्षणिक समीक्षा।",
        "results_ach": "विद्यार्थी उपलब्धियाँ और मुख्य बिंदु",
        "results_ach_1_title": "१००% आधारभूत संक्रमण",
        "results_ach_1_text": "प्रारंभिक बाल्यावस्था चरणों (प्ले, सीडलिंग, सैपलिंग और एडवांस्ड सैपलिंग) से प्राथमिक कक्षाओं तक निरंतर पड़ाव उपलब्धि।",
        "results_ach_2_title": "प्रतियोगी ओलंपियाड और प्रतियोगिताएँ",
        "results_ach_2_text": "क्षेत्रीय प्रतिभा परीक्षाओं, विज्ञान चुनौतियों और राष्ट्रीय ओलंपियाड मंचों में सक्रिय भागीदारी और सम्मान।",
        "results_ach_3_title": "सह-शैक्षणिक उत्कृष्टता",
        "results_ach_3_text": "वाद-विवाद, कला, खेल और सांस्कृतिक प्रस्तुतियों में अंतर-विद्यालय पुरस्कार।",
        "results_see": "अपना परिणाम देखें",
        "results_p1": "अंक विद्यालय के परिणाम ऐप में देखे जाते हैं। अभिभावक बच्चे का विवरण भरकर अंकतालिका खोलते हैं।",
        "results_p2": "आपको <strong>परीक्षा</strong> (प्रथम चरण, द्वितीय चरण, अर्धवार्षिक, तृतीय चरण या वार्षिक), <strong>कक्षा</strong>, <strong>अनुभाग</strong>, <strong>छात्र का नाम</strong> और <strong>रोल</strong> चाहिए।",
        "results_cta": "अपना परिणाम देखें",
        "results_p3": "यदि खोज मेल न खाए तो बच्चे का नाम और कक्षा लिखकर कार्यालय को {mail} पर लिखें।",
        "toppers": "टॉपर्स",
        "toppers_p": "प्रत्येक परीक्षा के बाद विद्यालय कक्षावार उत्कृष्टता का सम्मान करता है — एक चित्र और संक्षिप्त वचन, परिवार की सहमति से।",
        "topper_photo": "चित्र",
        "topper_said": "उनके शब्द",
        "class_play": "प्ले (प्री-नर्सरी)",
        "class_seedling": "सीडलिंग",
        "class_sapling": "सैपलिंग",
        "class_adv": "एडवांस्ड सैपलिंग",
        "class_1": "कक्षा १",
        "class_2": "कक्षा २",
        "class_3": "कक्षा ३",
        "class_4": "कक्षा ४",
        "class_5": "कक्षा ५",
        "class_6": "कक्षा ६",
        "class_7": "कक्षा ७",
        "class_8": "कक्षा ८",
        "class_1_5": "कक्षा १–५",
        "class_6_8": "कक्षा ६–८",
        "subj_early": "अंग्रेज़ी, हिंदी, गणित, ईवीएस, कला",
        "subj_adv": "अंग्रेज़ी, हिंदी, गणित, ईवीएस, कंप्यूटर",
        "subj_15": "अंग्रेज़ी, हिंदी, गणित, ईवीएस, कला, कंप्यूटर",
        "subj_68": "अंग्रेज़ी, हिंदी, गणित, विज्ञान, सामाजिक अध्ययन, संस्कृत, कंप्यूटर",
        "mail_subject_adm": "प्रवेश पूछताछ — एनपीएस धरहरा",
        "mail_subject_form": "विद्यालय पूछताछ — नूतन पब्लिक स्कूल, धरहरा",
        "fb_name": "नूतन पब्लिक स्कूल",
        "title_home": "नूतन पब्लिक स्कूल, धरहरा",
        "title_about": "परिचय · नूतन पब्लिक स्कूल, धरहरा",
        "title_academics": "शिक्षा · नूतन पब्लिक स्कूल, धरहरा",
        "title_life": "परिसर और विद्यार्थी जीवन · नूतन पब्लिक स्कूल, धरहरा",
        "title_facilities": "सुविधाएँ · नूतन पब्लिक स्कूल, धरहरा",
        "title_admissions": "प्रवेश · नूतन पब्लिक स्कूल, धरहरा",
        "title_results": "परिणाम · नूतन पब्लिक स्कूल, धरहरा",
        "title_faq": "प्रश्नोत्तर · नूतन पब्लिक स्कूल, धरहरा",
        "title_notices": "सूचनाएँ · नूतन पब्लिक स्कूल, धरहरा",
        "title_notices_archive": "सूचना संग्रह · नूतन पब्लिक स्कूल, धरहरा",
        "title_gallery": "गैलरी · नूतन पब्लिक स्कूल, धरहरा",
        "title_careers": "करियर · नूतन पब्लिक स्कूल, धरहरा",
        "title_reach": "कैसे पहुँचें · नूतन पब्लिक स्कूल, धरहरा",
        "title_rules": "नियम · नूतन पब्लिक स्कूल, धरहरा",
        "title_contact": "संपर्क · नूतन पब्लिक स्कूल, धरहरा",
        "og_about": "परिचय · एनपीएस धरहरा",
        "og_academics": "शिक्षा · एनपीएस धरहरा",
        "og_life": "परिसर और विद्यार्थी जीवन · एनपीएस धरहरा",
        "og_facilities": "सुविधाएँ · एनपीएस धरहरा",
        "og_admissions": "प्रवेश · एनपीएस धरहरा",
        "og_results": "परिणाम · एनपीएस धरहरा",
        "og_faq": "प्रश्नोत्तर · एनपीएस धरहरा",
        "og_notices": "सूचनाएँ · एनपीएस धरहरा",
        "og_gallery": "गैलरी · एनपीएस धरहरा",
        "og_careers": "करियर · एनपीएस धरहरा",
        "og_reach": "कैसे पहुँचें · एनपीएस धरहरा",
        "og_rules": "नियम · एनपीएस धरहरा",
        "og_contact": "संपर्क · एनपीएस धरहरा",
        "og_notice_fallback": "कार्यालय परिपत्र, नूतन पब्लिक स्कूल, धरहरा।",
    },
}


def t(lang: str, key: str) -> str:
    year = academic_year(lang)
    return UI[lang][key].replace("{year}", f'<span data-session-year>{year}</span>')
