"""English and Hindi chrome and page copy for the public school site."""

from datetime import date

_DEVANAGARI_DIGITS = str.maketrans("0123456789", "०१२३४५६७८९")


def academic_year(lang: str = "en") -> str:
    """Session label: current calendar year–next year's last two digits (e.g. 2026–27)."""
    year = date.today().year
    label = f"{year}–{str(year + 1)[-2:]}"
    if lang == "hi":
        return label.translate(_DEVANAGARI_DIGITS)
    return label


QUOTES = (
    {
        "image": "assets/quotes/vivekananda.png",
        "cite": {"en": "Swami Vivekananda", "hi": "स्वामी विवेकानंद"},
        "text": {
            "en": "Education is the manifestation of the perfection already in man.",
            "hi": "शिक्षा मनुष्य में पहले से विद्यमान पूर्णता का प्रकाश है।",
        },
    },
    {
        "image": "assets/quotes/kalam.png",
        "cite": {"en": "A. P. J. Abdul Kalam", "hi": "ए. पी. जे. अब्दुल कलाम"},
        "text": {
            "en": "The purpose of education is to make good human beings with skill and expertise. Enlightened human beings can be created by teachers.",
            "hi": "शिक्षा का उद्देश्य कुशलता और ज्ञान के साथ अच्छे मनुष्य बनाना है। प्रबुद्ध नागरिक शिक्षकों के मार्गदर्शन में गढ़े जाते हैं।",
        },
    },
    {
        "image": "assets/quotes/tagore.png",
        "cite": {"en": "Rabindranath Tagore", "hi": "रबीन्द्रनाथ ठाकुर"},
        "text": {
            "en": "The highest education is that which does not merely give us information but makes our life in harmony with all existence.",
            "hi": "सबसे ऊँची शिक्षा वह है जो केवल सूचना नहीं देती, बल्कि हमारे जीवन को सम्पूर्ण सृष्टि के साथ सामंजस्य में लाती है।",
        },
    },
    {
        "image": "assets/quotes/gandhi.png",
        "cite": {"en": "Mahatma Gandhi", "hi": "महात्मा गांधी"},
        "text": {
            "en": "Literacy in itself is no education. Literacy is not the end of education or even the beginning.",
            "hi": "साक्षरता अपने आप में शिक्षा नहीं है। साक्षरता शिक्षा का अंत नहीं है, न ही उसका आरंभ।",
        },
    },
    {
        "image": "assets/quotes/vivekananda.png",
        "cite": {"en": "Swami Vivekananda", "hi": "स्वामी विवेकानंद"},
        "text": {
            "en": "We want that education by which character is formed, strength of mind is increased, the intellect is expanded, and by which one can stand on one’s own feet.",
            "hi": "हम वह शिक्षा चाहते हैं जिससे चरित्र बने, मन बलवान हो, बुद्धि का विस्तार हो, और मनुष्य अपने पैरों पर खड़ा हो सके।",
        },
    },
    {
        "image": "assets/quotes/kalam.png",
        "cite": {"en": "A. P. J. Abdul Kalam", "hi": "ए. पी. जे. अब्दुल कलाम"},
        "text": {
            "en": "Learning gives creativity, creativity leads to thinking, thinking provides knowledge, and knowledge makes you great.",
            "hi": "सीखना सृजनशीलता देता है, सृजनशीलता सोच की ओर ले जाती है, सोच ज्ञान देती है, और ज्ञान मनुष्य को महान बनाता है।",
        },
    },
    {
        "image": "assets/quotes/radhakrishnan.png",
        "cite": {"en": "Dr S. Radhakrishnan", "hi": "डॉ. एस. राधाकृष्णन"},
        "text": {
            "en": "The true teachers are those who help us think for ourselves.",
            "hi": "सच्चे शिक्षक वे हैं जो हमें स्वयं सोचने में सहायता करते हैं।",
        },
    },
    {
        "image": "assets/quotes/vivekananda.png",
        "cite": {"en": "Swami Vivekananda", "hi": "स्वामी विवेकानंद"},
        "text": {
            "en": "Arise, awake, and stop not till the goal is reached.",
            "hi": "उठो, जागो और लक्ष्य प्राप्त होने तक रुको मत।",
        },
    },
    {
        "image": "assets/quotes/tagore.png",
        "cite": {"en": "Rabindranath Tagore", "hi": "रबीन्द्रनाथ ठाकुर"},
        "text": {
            "en": "Don’t limit a child to your own learning, for he was born in another time.",
            "hi": "बच्चे को अपनी शिक्षा की सीमा में न बाँधो; वह दूसरे समय में जन्मा है।",
        },
    },
    {
        "image": "assets/quotes/kalam.png",
        "cite": {"en": "A. P. J. Abdul Kalam", "hi": "ए. पी. जे. अब्दुल कलाम"},
        "text": {
            "en": "Dream, dream, dream. Dreams transform into thoughts and thoughts result in action.",
            "hi": "सपने देखो, सपने देखो, सपने देखो। सपने विचारों में बदलते हैं और विचार कर्म में।",
        },
    },
)

TOPPERS = (
    {
        "class_key": "class_seedling",
        "image": "assets/toppers/seedling.png",
        "name": {"en": "Aarav", "hi": "आरव"},
        "quote": {
            "en": "I like sitting in a circle and saying A, B, C. Didi claps when I finish my picture.",
            "hi": "मुझे घेरे में बैठकर अ, आ बोलना अच्छा लगता है। दीदी तस्वीर पूरी होने पर ताली बजाती हैं।",
        },
    },
    {
        "class_key": "class_sapling",
        "image": "assets/toppers/sapling.png",
        "name": {"en": "Vivaan", "hi": "विवान"},
        "quote": {
            "en": "I can write my name now. Maths is counting beads, and playtime is the best.",
            "hi": "अब मैं अपना नाम लिख लेता हूँ। गणित में मनके गिनते हैं, और खेल का समय सबसे अच्छा है।",
        },
    },
    {
        "class_key": "class_adv",
        "image": "assets/toppers/adv.png",
        "name": {"en": "Advik", "hi": "अद्विक"},
        "quote": {
            "en": "Computer class is new. I like pressing the keys and watching the letters come on the screen.",
            "hi": "कंप्यूटर की कक्षा नई है। मुझे बटन दबाना और स्क्रीन पर अक्षर आना अच्छा लगता है।",
        },
    },
    {
        "class_key": "class_1",
        "image": "assets/toppers/class-1.png",
        "name": {"en": "Ananya", "hi": "अनन्या"},
        "quote": {
            "en": "I read small sentences in English and Hindi. I want my handwriting to stay neat.",
            "hi": "मैं अंग्रेज़ी और हिंदी में छोटी पंक्तियाँ पढ़ती हूँ। मेरी लिखावट साफ़ रहे, यही चाहती हूँ।",
        },
    },
    {
        "class_key": "class_2",
        "image": "assets/toppers/class-2.png",
        "name": {"en": "Kabir", "hi": "कबीर"},
        "quote": {
            "en": "Tables are hard at first, then they stay in my head. I like EVS because we talk about plants.",
            "hi": "पहाड़े पहले कठिन लगते हैं, फिर याद रह जाते हैं। ईवीएस अच्छी लगती है क्योंकि हम पौधों की बात करते हैं।",
        },
    },
    {
        "class_key": "class_3",
        "image": "assets/toppers/class-3.png",
        "name": {"en": "Ishaan", "hi": "ईशान"},
        "quote": {
            "en": "Story period is my favourite. If I read a little every day, the long words get easier.",
            "hi": "कहानी की घड़ी सबसे प्यारी है। रोज़ थोड़ा पढ़ने से बड़े शब्द आसान हो जाते हैं।",
        },
    },
    {
        "class_key": "class_4",
        "image": "assets/toppers/class-4.png",
        "name": {"en": "Anjali", "hi": "अंजलि"},
        "quote": {
            "en": "I try to finish my work in class so I can play. Hindi and Maths both need practice at home.",
            "hi": "मैं कक्षा में काम पूरा करने की कोशिश करती हूँ, फिर खेलने मिलता है। हिंदी और गणित दोनों घर पर अभ्यास चाहते हैं।",
        },
    },
    {
        "class_key": "class_5",
        "image": "assets/toppers/class-5.png",
        "name": {"en": "Rohan", "hi": "रोहन"},
        "quote": {
            "en": "I like computer and art. When I revise in the evening, the test feels fair, not sudden.",
            "hi": "मुझे कंप्यूटर और कला अच्छे लगते हैं। शाम को दोहराव कर लूँ तो परीक्षा अचानक नहीं लगती।",
        },
    },
    {
        "class_key": "class_6",
        "image": "assets/toppers/class-6.png",
        "name": {"en": "Harsh", "hi": "हर्ष"},
        "quote": {
            "en": "Science experiments stay with me. Sanskrit is new, but the shlokas are fun to say aloud.",
            "hi": "विज्ञान के प्रयोग याद रह जाते हैं। संस्कृत नई है, पर श्लोक ज़ोर से बोलना मज़ेदार है।",
        },
    },
    {
        "class_key": "class_7",
        "image": "assets/toppers/class-7.png",
        "name": {"en": "Aditya", "hi": "आदित्य"},
        "quote": {
            "en": "I keep a small timetable at home. Maps in social studies and Maths problems both need quiet time.",
            "hi": "घर पर छोटी समय-सारिणी बनाता हूँ। सामाजिक अध्ययन के नक्शे और गणित के सवाल दोनों को शांत समय चाहिए।",
        },
    },
    {
        "class_key": "class_8",
        "image": "assets/toppers/class-8.png",
        "name": {"en": "Priya", "hi": "प्रिया"},
        "quote": {
            "en": "This year I want to be ready for the next school. Teachers say practice every day, not only before the exam.",
            "hi": "इस साल अगले विद्यालय के लिए तैयार रहना चाहती हूँ। शिक्षक कहते हैं रोज़ अभ्यास करो, केवल परीक्षा से पहले नहीं।",
        },
    },
)

NOTICE_HI = {
    "independence-day.txt": {
        "title": "स्वतंत्रता दिवस",
        "summary": "विद्यालय परिसर में राष्ट्रीय पर्व मनाया जाता है। सभा का समय कार्यालय से पुष्टि करें।",
        "body": (
            "नूतन पब्लिक स्कूल, धरहरा परिसर में स्वतंत्रता दिवस मनाता है।\n\n"
            "सभा का समय और दिनचर्या में कोई परिवर्तन कक्षा-शिक्षक तथा कार्यालय द्वारा सूचित किया जाता है। "
            "परिवारों से अनुरोध है कि कार्यालय से प्राप्त सूचना को अंतिम मानें।\n\n"
            "ईमेल पर परिपत्र पाने के लिए npsd1970@gmail.com पर लिखें।\n\n"
            "शैक्षणिक सत्र {year}।"
        ),
    },
    "ptm.txt": {
        "title": "अभिभावक–शिक्षक बैठक",
        "summary": "तिथि कक्षा-शिक्षक भेजते हैं। परिपत्र चाहिए तो कार्यालय को ईमेल करें।",
        "body": (
            "अभिभावक–शिक्षक बैठक की तिथि और समय कक्षा-शिक्षक सूचित करते हैं।\n\n"
            "यदि परिपत्र न मिले तो npsd1970@gmail.com पर लिखें या धरहरा स्थित कार्यालय से संपर्क करें। "
            "यह पृष्ठ बुकिंग फॉर्म नहीं है।\n\n"
            "कृपया सार्वजनिक फॉर्म के माध्यम से बच्चों के फोटो या पहचान पत्र न भेजें।\n\n"
            "शैक्षणिक सत्र {year}।"
        ),
    },
    "circulars-email.png": {
        "title": "परिपत्र कैसे पहुँचते हैं",
        "summary": "कार्यालय की ईमेल सूची में नाम लिखवाएँ: npsd1970@gmail.com।",
        "body": "",
    },
}

UI = {
    "en": {
        "html_lang": "en",
        "skip": "Skip to main content",
        "lang_label": "हिन्दी",
        "lang_title": "हिन्दी में देखें",
        "open_menu": "Open menu",
        "open_sub": "Show more pages",
        "nav_home": "Home",
        "nav_about": "About",
        "nav_about_school": "About the school",
        "nav_facilities": "Facilities",
        "nav_reach": "How to reach",
        "nav_rules": "Rules and conduct",
        "nav_academics": "Academics",
        "nav_classes": "Classes and subjects",
        "nav_life": "School life",
        "nav_admissions": "Admissions",
        "nav_enquire": "Enquire",
        "nav_faq": "FAQ",
        "nav_results": "Results",
        "nav_notices": "Notices",
        "nav_gallery": "Gallery",
        "nav_careers": "Careers",
        "nav_contact": "Contact",
        "brand": "Nootan Public School",
        "place": "Dharhara, Vaishali, Bihar (844117)",
        "footer_quick": "Quick links",
        "footer_school": "School",
        "footer_contact": "Contact",
        "footer_fb": "Nootan Public School",
        "footer_ig": "nps_dharhara_official",
        "footer_fb_aria": "Facebook: Nootan Public School",
        "footer_ig_aria": "Instagram: nps_dharhara_official",
        "map_open": "Open in Maps",
        "map_title": "Nootan Public School, Dharhara on Google Maps",
        "legal": "© Copyright {year} Nootan Public School, Dharhara<br />All Rights Reserved.",
        "crumbs_home": "Home",
        "site_desc": "Nootan Public School, Dharhara, Vaishali, Bihar — Seedling to Class 8.",
        "results_desc": "Look up a marksheet by examination, class, section, name, and roll.",
        "banner_about": "Our Legacy & Vision",
        "banner_academics": "Learning & growth",
        "banner_admissions": "Join our community",
        "banner_results": "Celebrating Excellence",
        "banner_notices": "Announcements & updates",
        "banner_gallery": "Moments & memories",
        "banner_careers": "Join our staff",
        "banner_contact": "Get in Touch",
        "banner_life": "School life",
        "banner_facilities": "Facilities",
        "banner_faq": "FAQ",
        "banner_reach": "How to reach",
        "banner_rules": "Rules and conduct",
        "crumb_about_school": "About the school",
        "crumb_classes": "Classes and subjects",
        "crumb_enquire": "Enquire",
        "crumb_from_office": "From the office",
        "crumb_campus": "Campus pictures",
        "crumb_write": "Write to the office",
        "crumb_marksheet": "Look up a marksheet",
        "home_about": "About the school",
        "home_about_p1": "Nootan Public School stands in Dharhara, Vaishali district, Bihar. It is a day school: children attend for the working day and return home. There is no hostel on this campus.",
        "home_about_p2": "The school offers a continuous path from Seedling through Class 8. Early years — Seedling, Sapling, and Advanced Sapling — introduce letters, numbers, language, and classroom habit. Classes 1 to 8 follow a fuller timetable: languages, mathematics, environmental or science studies, and computer from Advanced Sapling onward. Lessons are in Hindi and English; office circulars may be in either language.",
        "home_about_p3": "Education here forms character as well as skill — attendance, courtesy, finished work, and fairness toward classmates. The school draws inspiration from Swami Vivekananda on education and self-reliance. NPS is an independent campus in Dharhara, not a branch of Ramakrishna Mission; the quotations on this site are a public homage.",
        "home_about_p4": "These pages are for guardians: classes, campus life, admission enquiries, office circulars, and results. For a record that is not on the public lookup, write to the office.",
        "home_about_more": "Read the full about page",
        "home_explore": "Explore",
        "home_start": "Where to start",
        "card_academics": "Seedling to Class 8, with subjects and examinations at every stage.",
        "card_results": "Open a marksheet by examination, class, section, name, and roll.",
        "card_admissions": "Enquire by email or visit the office. Fees are not taken on this website.",
        "card_contact": "Write to npsd1970@gmail.com for circulars and admissions.",
        "card_facilities": "Classrooms, playground, and computer from Advanced Sapling.",
        "card_life": "Assembly, Hindi and English, sport, and art as part of the school day.",
        "card_notices": "Read circulars from the office — holidays, meetings, and session dates.",
        "home_campus": "Campus and school day",
        "home_campus_p1": "Teaching takes place in classrooms on the Dharhara campus, with open ground for play. Computer is on the timetable from Advanced Sapling. Art sits beside books in the younger classes; from Class 6, science, social studies, and Sanskrit join the list.",
        "home_campus_p2": "A typical day begins with assembly, then lessons, then time outdoors. Sport is part of education — fitness, fair play, and showing up. For a specific facility for your child, write to the office.",
        "home_notices_label": "Notices",
        "home_notices_title": "From the office",
        "home_notices_note": "Read circulars issued by the office. Open a notice for the full text. See all on the {link}.",
        "home_notices_link": "notices page",
        "home_help": "How can we help?",
        "home_help_p": "For admission, a circular, or a visit to the office, write to the school email. Fees are not collected on this website.",
        "home_help_cta": "Enquire for admission",
        "home_help_mail": "Write to npsd1970@gmail.com",
        "no_notices": "No circulars are listed at present. Write to npsd1970@gmail.com to join the office mailing list.",
        "all_notices": "All notices",
        "notice_circular": "Office circular",
        "about_who": "Who we are",
        "about_who_p1": "Nootan Public School (NPS) is a day school in Dharhara, Vaishali district, Bihar. In Hindi the school is known as नूतन पब्लिक स्कूल, धरहरा.",
        "about_who_p2": "We offer a single path from Seedling through Class 8. Early childhood, primary, and the first years of middle school sit on one campus, so a child can grow through stages without changing institution. Lessons use Hindi and English. Circulars may be in either language.",
        "about_aim": "Aim of the school",
        "about_aim_p1": "The daily work is attendance, classwork, homework a child can finish, and a calm assembly. We want children who can read, count, speak, and stand on their own feet. Honesty, courtesy, and effort are treated as part of education.",
        "about_aim_p2": "The home page quotes Swami Vivekananda because those lines speak to education as the drawing-out of what is already in the child. They are an inspiration. This campus is Nootan Public School, Dharhara — not a branch of Ramakrishna Mission.",
        "about_web": "These pages",
        "about_web_p1": "Guardians will find classes, school life, facilities, admission, and office circulars here. The academic year shown is <strong>{year}</strong>. Marks are looked up on the {results} page.",
        "acad_path": "Classes and a continuous path",
        "acad_path_p1": "The school teaches Seedling through Class 8 as one sequence. Seedling and Sapling introduce language, number, and classroom routine. Advanced Sapling adds computer as a subject. Classes 1 to 5 keep English, Hindi, mathematics, environmental studies, art, and computer. Classes 6 to 8 widen the map: science and social studies in place of EVS, Sanskrit beside Hindi, and computer continuing through the timetable.",
        "acad_path_p2": "Marks and class rank are recorded for the office and for parents. Look up a child’s marksheet on the {results} page.",
        "acad_exams": "Examinations",
        "acad_exams_p": "The year is examined in five stages: <strong>1st Term</strong>, <strong>2nd Term</strong>, <strong>Half Yearly</strong>, <strong>3rd Term</strong>, and <strong>Annual</strong>. Dates for each paper are issued as circulars.",
        "acad_cal": "Academic calendar {year}",
        "acad_cal_p": "The session shown on this site is {year}. Holidays, parent–teacher meetings, and assembly days are issued by the office. Open the {notices} for current circulars, and treat a message from the office as the calendar that counts.",
        "acad_lang": "Language and method",
        "acad_lang_p": "Classroom work uses Hindi and English. Circulars may arrive in either language; if a notice is unclear, write to npsd1970@gmail.com. Homework is meant to be finishable. Questions about extra help for a particular child belong with the class teacher or the office.",
        "acad_seat": "Enquire for a seat",
        "life_day": "A day at school",
        "life_day_p1": "The day begins with assembly: standing together, a short address or prayer as the office arranges, then classes. Lessons move between Hindi and English. Younger children have art in the timetable; older children have science, social studies, and Sanskrit as well as the languages and mathematics they already know.",
        "life_day_p2": "Play is part of the day. There is ground on campus. Sport here means turning up, playing fairly, and keeping the body in the habit of movement.",
        "life_fest": "Festivals and gatherings",
        "life_fest_p": "National days and school gatherings are observed on campus. Exact times go out as circulars — by class teacher, by email if you are on the office list, or on paper from the office. Open a notice for the full text or image.",
        "life_uniform": "Uniform and books",
        "life_uniform_p": "The pattern of the uniform and the book list for the year are issued by the office. Ask when you enquire, or write to npsd1970@gmail.com.",
        "life_photo": "Photographs",
        "life_photo_p": "Campus views appear in the gallery. Children’s portraits are published only with the school’s care for privacy, never as a public roll of names.",
        "fac_on": "On campus",
        "fac_on_p1": "The campus in Dharhara holds classrooms for Seedling through Class 8 and open ground for play. Computer is taught from Advanced Sapling onward. Children attend for the school day and return home; this is a day school, not a boarding campus.",
        "fac_on_p2": "Rooms are for teaching and gathering. If a particular room or resource matters for admission this year, the office will confirm it in writing.",
        "fac_more": "Asking the office",
        "fac_more_p": "Hostel, paid extra courses, transport routes, and visiting hours are confirmed by the office for the current year. Write if you need those details before a visit.",
        "ask_office": "Ask the office",
        "adm_year": "Academic year {year}",
        "adm_year_p1": "Seats are considered for Seedling through Class 8. Admission is an office process: a conversation, the papers the school asks for, and the fee rules explained in person or by email. There is no online application that takes money on this website.",
        "adm_year_p2": "Age and previous class matter. The office will advise whether a child can join Seedling, a later early-years group, or a numbered class. Fee amounts are given in an official note, not as a public table.",
        "adm_how": "How to enquire",
        "adm_how_p": "Email {mail} with the child’s name, age or class sought, and a phone number the office can use. You may visit the school in Dharhara — write first so someone can receive you. The contact page form opens Gmail with the school address already filled.",
        "adm_papers": "Papers the office usually asks for",
        "adm_papers_p": "After first contact the office will confirm the list for this year. Families are often asked for proof of the child’s age or class, and — if the child is moving from another school — a leaving record from that school. Identity documents belong at the office, on paper or by the channel the office names.",
        "adm_uniform_p": "Uniform pattern and the book list are issued by the office. Ask when you enquire.",
        "adm_tc": "Transfer or leaving certificate",
        "adm_tc_p": "A transfer or leaving certificate is issued at the office. Write or visit and ask for the steps for this year.",
        "adm_faq": "Admission FAQ",
        "adm_write": "Write to the office",
        "adm_write_p": "Admission enquiries go to the school email.",
        "faq_q": "Questions",
        "faq_q1": "Which classes do you teach?",
        "faq_a1": "Seedling, Sapling, Advanced Sapling, and Class 1 through Class 8, as a day school on the Dharhara campus.",
        "faq_q2": "How do I apply?",
        "faq_a2": "Email npsd1970@gmail.com with the child’s name, age or class sought, and a phone number, or visit the office. There is no online form that takes fees.",
        "faq_q3": "Can I pay fees on this website?",
        "faq_a3": "No. Fees are handled by the office and are set out in an official note.",
        "faq_q4": "Where are marks and attendance?",
        "faq_a4": "Open the Results page and look up with examination, class, section, name, and roll. Attendance stays with the office.",
        "faq_q5": "How do I get a transfer certificate?",
        "faq_a5": "Apply at the office. There is no TC form on this website.",
        "faq_q6": "Where is the academic calendar?",
        "faq_a6": "The year shown is {year}. Holiday and meeting dates go out as circulars. Open the notice boxes, or ask the office.",
        "faq_q7": "How are photographs used on this site?",
        "faq_a7": "The gallery presents campus views issued by the school. Children’s portraits are not used as a public roll of names.",
        "notices_from": "From the office",
        "notices_p": "Circulars — holidays, parent meetings, session dates — go to class teachers and, when you ask, to email. Open a notice for the full text or image. Write to npsd1970@gmail.com to join the mailing list.",
        "gal_h": "Campus pictures",
        "gal_p": "The gallery presents the Dharhara campus — classrooms, grounds, and gathering spaces. Open a section to see photographs issued by the school. Children’s names are not published under a photograph.",
        "gal_1": "Classrooms",
        "gal_2": "Playground",
        "gal_3": "Assembly",
        "gal_4": "Campus",
        "gal_5": "Activities",
        "gal_6": "Office",
        "gal_empty": "Photographs for this album will appear here.",
        "gal_all": "All albums",
        "reach_place": "Place",
        "reach_p": "Nootan Public School is in Dharhara, Vaishali district, Bihar. Children attend for the day and return home. If you are travelling from Hajipur, Muzaffarpur, or a nearby village, write first so the office can tell you when someone will be there to receive you.",
        "reach_follow": "Write or follow",
        "rules_in": "In school",
        "rules_in_p": "Children are expected to attend, arrive ready for the day, speak with courtesy, and finish the work that is set. Assembly is part of the school day. Hindi and English are both used in class.",
        "rules_circ": "Circulars",
        "rules_circ_p": "Holidays, meetings, and changes of routine go out as circulars: on this website, through the class teacher, and by email if you ask to be on the list (npsd1970@gmail.com). Facebook and Instagram carry messages the office chooses to post. A paper or email from the office is the notice that counts.",
        "rules_visit": "Visiting",
        "rules_visit_p": "Write or call at the office before a visit so someone can receive you. Visiting hours are confirmed by the office for the current year.",
        "rules_priv": "Privacy",
        "rules_priv_p": "Student lists are not published on these pages. The gallery is reserved for campus views issued by the school. Conduct here is a public summary; the office may add a printed note for the year.",
        "contact_school": "School",
        "contact_school_name": "Nootan Public School, Dharhara · नूतन पब्लिक स्कूल, धरहरा",
        "contact_place_l": "Place",
        "contact_email_l": "Email",
        "contact_circ": "How circulars reach you",
        "contact_circ_p": "Open the notice boxes on this site, ask the class teacher, write to npsd1970@gmail.com to join the email list, or follow the school Facebook and Instagram pages.",
        "contact_write": "Write from this page",
        "contact_write_p": "Fill in the same questions as the school inquiry form. Submit sends your answers to the office. Nothing is stored on this website.",
        "form_student": "Full name of student",
        "form_father": "Father’s name",
        "form_mother": "Mother’s name",
        "form_phone": "Contact number",
        "form_email": "Parent email address",
        "form_grade": "Grade applying for",
        "form_inquiry": "Inquiry type",
        "form_choose": "Choose…",
        "form_query": "Please detail your query",
        "form_submit": "Submit",
        "form_thanks": "Thank you. The office has received your message.",
        "form_required_meaning": "mandatory",
        "form_required_abbr": "Mandatory",
        "form_grade_pre": "Pre-Nursery",
        "form_grade_seedling": "Seedling (Nursery)",
        "form_grade_sapling": "Sapling (LKG)",
        "form_grade_adv": "Advance Sapling (UKG)",
        "form_grade_1": "Class 1",
        "form_grade_2": "Class 2",
        "form_grade_3": "Class 3",
        "form_grade_4": "Class 4",
        "form_grade_5": "Class 5",
        "form_grade_6": "Class 6",
        "form_grade_7": "Class 7",
        "form_grade_8": "Class 8",
        "form_inq_adm": "Admission process",
        "form_inq_fee": "Fee structure",
        "form_inq_exam": "Exam schedule",
        "form_inq_other": "Other",
        "careers_intro": "The school considers teachers for the subjects it runs — languages, mathematics, science, social studies, computer, arts, and physical education. Apply below; Submit sends your application to the office.",
        "careers_apply": "Apply to teach",
        "careers_name": "Full name",
        "careers_address": "Place / address",
        "careers_age": "Age",
        "careers_gender": "Gender",
        "careers_qual": "Highest education qualification",
        "careers_workplace": "Last workplace",
        "careers_salary": "Expected salary (monthly)",
        "careers_subjects": "Subjects you can teach",
        "careers_subject_other": "Other subject (if any)",
        "careers_classes": "Classes you are qualified to teach",
        "careers_sample": "Link to a sample lesson plan or teaching video",
        "careers_thanks": "Thank you. The office has received your application.",
        "form_gender_male": "Male",
        "form_gender_female": "Female",
        "form_gender_other": "Other",
        "form_qual_bed": "Bachelor of Education (B.Ed)",
        "form_qual_med": "Master of Education (M.Ed)",
        "form_qual_pg": "Post Graduate (PG)",
        "form_qual_ug": "Graduate (UG)",
        "form_qual_other": "Other",
        "form_sub_math": "Mathematics",
        "form_sub_sci": "Science",
        "form_sub_eng": "English",
        "form_sub_hin": "Hindi",
        "form_sub_sst": "Social Studies",
        "form_sub_comp": "Computer",
        "form_sub_art": "Arts and Physical Education",
        "form_sub_evs": "EVS",
        "form_cls_pre": "Pre-Primary (Nursery–KG)",
        "form_cls_pri": "Primary (1–5)",
        "form_cls_mid": "Middle School (6–8)",
        "crumb_apply": "Apply to teach",
        "results_see": "See your results",
        "results_p1": "Marks are looked up in the school results app. Guardians enter the child’s details and open the marksheet.",
        "results_p2": "You will need the <strong>examination</strong> (1st Term, 2nd Term, Half Yearly, 3rd Term, or Annual), <strong>class</strong>, <strong>section</strong>, <strong>student name</strong>, and <strong>roll</strong>.",
        "results_cta": "See your results",
        "results_p3": "If the lookup does not match, write to the office at {mail} with the child’s name and class.",
        "toppers": "Toppers",
        "toppers_p": "After each examination the school honours class-wise distinction — a portrait and a short word, shared with the family’s consent.",
        "topper_photo": "Portrait",
        "topper_said": "In their words",
        "class_seedling": "Seedling",
        "class_sapling": "Sapling",
        "class_adv": "Advanced Sapling",
        "class_1": "Class 1",
        "class_2": "Class 2",
        "class_3": "Class 3",
        "class_4": "Class 4",
        "class_5": "Class 5",
        "class_6": "Class 6",
        "class_7": "Class 7",
        "class_8": "Class 8",
        "class_1_5": "Class 1–5",
        "class_6_8": "Class 6–8",
        "subj_early": "English, Hindi, Maths, EVS, Art",
        "subj_adv": "English, Hindi, Maths, EVS, Computer",
        "subj_15": "English, Hindi, Maths, EVS, Art, Computer",
        "subj_68": "English, Hindi, Maths, Science, Social Studies, Sanskrit, Computer",
        "mail_subject_adm": "Admission enquiry — NPS Dharhara",
        "mail_subject_form": "School enquiry — Nootan Public School, Dharhara",
        "fb_name": "Nootan Public School",
        "title_home": "Nootan Public School, Dharhara",
        "title_about": "About · Nootan Public School, Dharhara",
        "title_academics": "Academics · Nootan Public School, Dharhara",
        "title_life": "School life · Nootan Public School, Dharhara",
        "title_facilities": "Facilities · Nootan Public School, Dharhara",
        "title_admissions": "Admissions · Nootan Public School, Dharhara",
        "title_results": "Results · Nootan Public School, Dharhara",
        "title_faq": "FAQ · Nootan Public School, Dharhara",
        "title_notices": "Notices · Nootan Public School, Dharhara",
        "title_gallery": "Gallery · Nootan Public School, Dharhara",
        "title_careers": "Careers · Nootan Public School, Dharhara",
        "title_reach": "How to reach · Nootan Public School, Dharhara",
        "title_rules": "Rules · Nootan Public School, Dharhara",
        "title_contact": "Contact · Nootan Public School, Dharhara",
        "og_about": "About · NPS Dharhara",
        "og_academics": "Academics · NPS Dharhara",
        "og_life": "School life · NPS Dharhara",
        "og_facilities": "Facilities · NPS Dharhara",
        "og_admissions": "Admissions · NPS Dharhara",
        "og_results": "Results · NPS Dharhara",
        "og_faq": "FAQ · NPS Dharhara",
        "og_notices": "Notices · NPS Dharhara",
        "og_gallery": "Gallery · NPS Dharhara",
        "og_careers": "Careers · NPS Dharhara",
        "og_reach": "How to reach · NPS Dharhara",
        "og_rules": "Rules · NPS Dharhara",
        "og_contact": "Contact · NPS Dharhara",
        "og_notice_fallback": "Office circular, Nootan Public School, Dharhara.",
    },
    "hi": {
        "html_lang": "hi",
        "skip": "मुख्य विषय पर जाएँ",
        "lang_label": "अंग्रेज़ी",
        "lang_title": "अंग्रेज़ी में देखें",
        "open_menu": "मेनू खोलें",
        "open_sub": "और पृष्ठ दिखाएँ",
        "nav_home": "मुखपृष्ठ",
        "nav_about": "परिचय",
        "nav_about_school": "विद्यालय के बारे में",
        "nav_facilities": "सुविधाएँ",
        "nav_reach": "कैसे पहुँचें",
        "nav_rules": "नियम और आचरण",
        "nav_academics": "शिक्षा",
        "nav_classes": "कक्षाएँ और विषय",
        "nav_life": "विद्यालय जीवन",
        "nav_admissions": "प्रवेश",
        "nav_enquire": "पूछताछ",
        "nav_faq": "प्रश्नोत्तर",
        "nav_results": "परिणाम",
        "nav_notices": "सूचनाएँ",
        "nav_gallery": "गैलरी",
        "nav_careers": "करियर",
        "nav_contact": "संपर्क",
        "brand": "नूतन पब्लिक स्कूल",
        "place": "धरहरा, वैशाली, बिहार (844117)",
        "footer_quick": "त्वरित लिंक",
        "footer_school": "विद्यालय",
        "footer_contact": "संपर्क",
        "footer_fb": "नूतन पब्लिक स्कूल",
        "footer_ig": "nps_dharhara_official",
        "footer_fb_aria": "फेसबुक: नूतन पब्लिक स्कूल",
        "footer_ig_aria": "इंस्टाग्राम: nps_dharhara_official",
        "map_open": "मानचित्र में खोलें",
        "map_title": "नूतन पब्लिक स्कूल, धरहरा — गूगल मैप",
        "legal": "© कॉपीराइट {year} नूतन पब्लिक स्कूल, धरहरा<br />सर्वाधिकार सुरक्षित।",
        "crumbs_home": "मुखपृष्ठ",
        "site_desc": "नूतन पब्लिक स्कूल, धरहरा, वैशाली, बिहार — सीडलिंग से कक्षा ८ तक।",
        "results_desc": "परीक्षा, कक्षा, अनुभाग, नाम और रोल से अंकतालिका देखें।",
        "banner_about": "हमारी विरासत और दृष्टि",
        "banner_academics": "शिक्षा और विकास",
        "banner_admissions": "हमारे समुदाय से जुड़ें",
        "banner_results": "उत्कृष्टता का सम्मान",
        "banner_notices": "सूचनाएँ और अद्यतन",
        "banner_gallery": "पल और स्मृतियाँ",
        "banner_careers": "स्टाफ में शामिल हों",
        "banner_contact": "संपर्क करें",
        "banner_life": "विद्यालय जीवन",
        "banner_facilities": "सुविधाएँ",
        "banner_faq": "प्रश्नोत्तर",
        "banner_reach": "कैसे पहुँचें",
        "banner_rules": "नियम और आचरण",
        "crumb_about_school": "विद्यालय के बारे में",
        "crumb_classes": "कक्षाएँ और विषय",
        "crumb_enquire": "पूछताछ",
        "crumb_from_office": "कार्यालय से",
        "crumb_campus": "परिसर के चित्र",
        "crumb_write": "कार्यालय को लिखें",
        "crumb_marksheet": "अंकतालिका देखें",
        "home_about": "विद्यालय के बारे में",
        "home_about_p1": "नूतन पब्लिक स्कूल वैशाली जिले के धरहरा में स्थित है। यह दिवसीय विद्यालय है: बच्चे पढ़ाई के दिन आते हैं और घर लौटते हैं। इस परिसर में छात्रावास नहीं है।",
        "home_about_p2": "विद्यालय सीडलिंग से कक्षा ८ तक एक सतत पथ देता है। प्रारंभिक वर्ष — सीडलिंग, सैपलिंग और एडवांस्ड सैपलिंग — अक्षर, संख्या, भाषा और कक्षा की आदत सिखाते हैं। कक्षा १ से ८ तक भाषा, गणित, पर्यावरण या विज्ञान, तथा एडवांस्ड सैपलिंग से कंप्यूटर। कक्षा हिंदी और अंग्रेज़ी में चलती है; परिपत्र दोनों भाषाओं में आ सकते हैं।",
        "home_about_p3": "यहाँ शिक्षा चरित्र और कौशल दोनों गढ़ती है — उपस्थिति, शिष्टाचार, पूरा किया गया कार्य और सहपाठियों के प्रति न्याय। विद्यालय स्वामी विवेकानंद के शिक्षा और आत्मनिर्भरता के विचारों से प्रेरणा लेता है। एनपीएस धरहरा का स्वतंत्र परिसर है, रामकृष्ण मिशन की शाखा नहीं; यहाँ के उद्धरण सार्वजनिक श्रद्धांजलि हैं।",
        "home_about_p4": "ये पृष्ठ अभिभावकों के लिए हैं: कक्षाएँ, परिसर जीवन, प्रवेश पूछताछ, कार्यालय परिपत्र और परिणाम। सार्वजनिक खोज में न हो तो कार्यालय को लिखें।",
        "home_about_more": "पूरा परिचय पढ़ें",
        "home_explore": "जानें",
        "home_start": "यहाँ से शुरू करें",
        "card_academics": "सीडलिंग से कक्षा ८ तक, प्रत्येक स्तर पर विषय और परीक्षाएँ।",
        "card_results": "परीक्षा, कक्षा, अनुभाग, नाम और रोल से अंकतालिका खोलें।",
        "card_admissions": "ईमेल या कार्यालय आकर पूछताछ करें। इस वेबसाइट पर शुल्क नहीं लिया जाता।",
        "card_contact": "परिपत्र और प्रवेश के लिए npsd1970@gmail.com पर लिखें।",
        "card_facilities": "कक्षाएँ, खेल मैदान, और एडवांस्ड सैपलिंग से कंप्यूटर।",
        "card_life": "प्रार्थना सभा, हिंदी और अंग्रेज़ी, खेल और कला — विद्यालय के दिन का हिस्सा।",
        "card_notices": "कार्यालय के परिपत्र पढ़ें — अवकाश, बैठकें और सत्र तिथियाँ।",
        "home_campus": "परिसर और विद्यालय दिवस",
        "home_campus_p1": "पढ़ाई धरहरा परिसर की कक्षाओं में होती है, खेल के लिए खुला मैदान है। एडवांस्ड सैपलिंग से कंप्यूटर समयसारणी में है। छोटी कक्षाओं में कला पुस्तकों के साथ है; कक्षा ६ से विज्ञान, सामाजिक अध्ययन और संस्कृत जुड़ते हैं।",
        "home_campus_p2": "दिन सभा से शुरू होता है, फिर पाठ, फिर बाहर का समय। खेल शिक्षा का भाग है — स्वास्थ्य, निष्पक्ष खेल और उपस्थित रहना। किसी विशेष सुविधा के लिए कार्यालय को लिखें।",
        "home_notices_label": "सूचनाएँ",
        "home_notices_title": "कार्यालय से",
        "home_notices_note": "कार्यालय द्वारा जारी परिपत्र पढ़ें। पूरा पाठ देखने के लिए सूचना खोलें। सभी {link} पर हैं।",
        "home_notices_link": "सूचना पृष्ठ",
        "home_help": "हम कैसे सहायता करें?",
        "home_help_p": "प्रवेश, परिपत्र या कार्यालय आने के लिए विद्यालय ईमेल पर लिखें। इस वेबसाइट पर शुल्क नहीं लिया जाता।",
        "home_help_cta": "प्रवेश पूछताछ",
        "home_help_mail": "npsd1970@gmail.com पर लिखें",
        "no_notices": "इस समय कोई परिपत्र सूचीबद्ध नहीं है। कार्यालय सूची में नाम लिखवाने के लिए npsd1970@gmail.com पर लिखें।",
        "all_notices": "सभी सूचनाएँ",
        "notice_circular": "कार्यालय परिपत्र",
        "about_who": "हम कौन हैं",
        "about_who_p1": "नूतन पब्लिक स्कूल (एनपीएस) वैशाली जिले के धरहरा में एक दिवसीय विद्यालय है। हिंदी में विद्यालय नूतन पब्लिक स्कूल, धरहरा के नाम से जाना जाता है।",
        "about_who_p2": "हम सीडलिंग से कक्षा ८ तक एक ही पथ देते हैं। प्रारंभिक बचपन, प्राथमिक और माध्यमिक के आरंभिक वर्ष एक परिसर पर हैं, ताकि बच्चा संस्था बदले बिना आगे बढ़े। पाठ हिंदी और अंग्रेज़ी में होते हैं। परिपत्र दोनों भाषाओं में आ सकते हैं।",
        "about_aim": "विद्यालय का उद्देश्य",
        "about_aim_p1": "दैनिक कार्य उपस्थिति, कक्षा कार्य, ऐसा गृहकार्य जिसे बच्चा पूरा कर सके, और शांत सभा है। हम चाहते हैं कि बच्चे पढ़ सकें, गिन सकें, बोल सकें और अपने पैरों पर खड़े हों। ईमानदारी, शिष्टाचार और परिश्रम शिक्षा का भाग हैं।",
        "about_aim_p2": "मुखपृष्ठ पर स्वामी विवेकानंद के वचन इसलिए हैं कि शिक्षा बच्चे में पहले से विद्यमान पूर्णता को प्रकट करती है। यह प्रेरणा है। यह परिसर नूतन पब्लिक स्कूल, धरहरा है — रामकृष्ण मिशन की शाखा नहीं।",
        "about_web": "ये पृष्ठ",
        "about_web_p1": "अभिभावकों को यहाँ कक्षाएँ, विद्यालय जीवन, सुविधाएँ, प्रवेश और कार्यालय परिपत्र मिलेंगे। दर्शाया गया सत्र <strong>{year}</strong> है। अंक {results} पृष्ठ पर देखे जाते हैं।",
        "acad_path": "कक्षाएँ और सतत पथ",
        "acad_path_p1": "विद्यालय सीडलिंग से कक्षा ८ तक एक क्रम में पढ़ाता है। सीडलिंग और सैपलिंग भाषा, संख्या और कक्षा की दिनचर्या सिखाते हैं। एडवांस्ड सैपलिंग में कंप्यूटर विषय जुड़ता है। कक्षा १ से ५ तक अंग्रेज़ी, हिंदी, गणित, पर्यावरण अध्ययन, कला और कंप्यूटर। कक्षा ६ से ८ में विज्ञान और सामाजिक अध्ययन, हिंदी के साथ संस्कृत, और कंप्यूटर समयसारणी में रहता है।",
        "acad_path_p2": "अंक और श्रेणी कार्यालय तथा अभिभावकों के लिए दर्ज होते हैं। बच्चे की अंकतालिका {results} पृष्ठ पर देखें।",
        "acad_exams": "परीक्षाएँ",
        "acad_exams_p": "वर्ष पाँच चरणों में परीक्षित होता है: <strong>प्रथम चरण</strong>, <strong>द्वितीय चरण</strong>, <strong>अर्धवार्षिक</strong>, <strong>तृतीय चरण</strong> और <strong>वार्षिक</strong>। प्रत्येक पत्र की तिथि परिपत्र से जाती है।",
        "acad_cal": "शैक्षणिक कैलेंडर {year}",
        "acad_cal_p": "इस साइट पर दिखाया गया सत्र {year} है। अवकाश, अभिभावक–शिक्षक बैठक और सभा के दिन कार्यालय जारी करता है। चालू परिपत्र {notices} में खोलें, और कार्यालय के संदेश को ही कैलेंडर मानें।",
        "acad_lang": "भाषा और विधि",
        "acad_lang_p": "कक्षा कार्य हिंदी और अंग्रेज़ी में होता है। परिपत्र किसी भी भाषा में आ सकते हैं; यदि सूचना स्पष्ट न हो तो npsd1970@gmail.com पर लिखें। गृहकार्य पूरा करने योग्य होना चाहिए। विशेष सहायता के प्रश्न कक्षा-शिक्षक या कार्यालय के हैं।",
        "acad_seat": "सीट के लिए पूछताछ",
        "life_day": "विद्यालय में एक दिन",
        "life_day_p1": "दिन सभा से शुरू होता है: साथ खड़े होना, कार्यालय द्वारा निर्धारित संबोधन या प्रार्थना, फिर कक्षाएँ। पाठ हिंदी और अंग्रेज़ी के बीच चलते हैं। छोटी कक्षाओं में कला है; बड़ी कक्षाओं में विज्ञान, सामाजिक अध्ययन और संस्कृत भी हैं।",
        "life_day_p2": "खेल दिन का हिस्सा है। परिसर में मैदान है। यहाँ खेल का अर्थ है उपस्थित रहना, निष्पक्ष खेलना और शरीर को गति की आदत में रखना।",
        "life_fest": "पर्व और आयोजन",
        "life_fest_p": "राष्ट्रीय दिवस और विद्यालय आयोजन परिसर में मनाए जाते हैं। सही समय परिपत्र से जाता है — कक्षा-शिक्षक, ईमेल सूची या कार्यालय के कागज से। पूरा पाठ या चित्र सूचना में खोलें।",
        "life_uniform": "वर्दी और पुस्तकें",
        "life_uniform_p": "वर्दी का स्वरूप और वर्ष की पुस्तक सूची कार्यालय जारी करता है। पूछताछ करते समय पूछें, या npsd1970@gmail.com पर लिखें।",
        "life_photo": "चित्र",
        "life_photo_p": "परिसर के दृश्य गैलरी में हैं। बच्चों के चित्र विद्यालय की गोपनीयता की नीति के साथ ही प्रकाशित होते हैं, सार्वजनिक नाम-सूची के रूप में नहीं।",
        "fac_on": "परिसर पर",
        "fac_on_p1": "धरहरा परिसर में सीडलिंग से कक्षा ८ तक कक्षाएँ और खेल का खुला मैदान है। एडवांस्ड सैपलिंग से कंप्यूटर पढ़ाया जाता है। बच्चे विद्यालय दिवस के लिए आते हैं और घर लौटते हैं; यह दिवसीय विद्यालय है, आवासीय नहीं।",
        "fac_on_p2": "कक्ष पढ़ाई और सभा के लिए हैं। यदि इस वर्ष प्रवेश के लिए कोई विशेष कक्ष या संसाधन आवश्यक है, तो कार्यालय लिखित रूप से पुष्टि करेगा।",
        "fac_more": "कार्यालय से पूछें",
        "fac_more_p": "छात्रावास, अतिरिक्त सशुल्क पाठ्यक्रम, परिवहन मार्ग और मुलाकात समय चालू वर्ष के लिए कार्यालय पुष्टि करता है। आने से पहले विवरण चाहिए तो लिखें।",
        "ask_office": "कार्यालय से पूछें",
        "adm_year": "शैक्षणिक सत्र {year}",
        "adm_year_p1": "सीडलिंग से कक्षा ८ तक सीटें विचारित होती हैं। प्रवेश कार्यालय की प्रक्रिया है: बातचीत, विद्यालय द्वारा मांगे गए कागजात, और व्यक्तिगत या ईमेल से बताए गए शुल्क नियम। इस वेबसाइट पर धन लेने वाला आवेदन नहीं है।",
        "adm_year_p2": "आयु और पिछली कक्षा मायने रखती है। कार्यालय बताएगा कि बच्चा सीडलिंग, बाद के प्रारंभिक समूह या क्रमांकित कक्षा में जा सकता है। शुल्क राशि आधिकारिक नोट में दी जाती है, सार्वजनिक तालिका में नहीं।",
        "adm_how": "पूछताछ कैसे करें",
        "adm_how_p": "{mail} पर बच्चे का नाम, आयु या वांछित कक्षा, और एक फोन नंबर भेजें। धरहरा आकर भी मिल सकते हैं — पहले लिखें ताकि कोई आपका स्वागत कर सके। संपर्क पृष्ठ का फॉर्म विद्यालय पते के साथ जीमेल खोलता है।",
        "adm_papers": "कार्यालय आमतौर पर जो कागजात माँगता है",
        "adm_papers_p": "पहली बातचीत के बाद कार्यालय इस वर्ष की सूची पुष्टि करेगा। प्रायः बच्चे की आयु या कक्षा का प्रमाण माँगा जाता है, और यदि बच्चा दूसरे विद्यालय से आ रहा है तो वहाँ का स्थानांतरण प्रमाण। पहचान पत्र कार्यालय में, कागज पर या कार्यालय द्वारा बताए गए माध्यम से दें।",
        "adm_uniform_p": "वर्दी और पुस्तक सूची कार्यालय जारी करता है। पूछताछ करते समय पूछें।",
        "adm_tc": "स्थानांतरण या स्थानत्याग प्रमाणपत्र",
        "adm_tc_p": "स्थानांतरण या स्थानत्याग प्रमाणपत्र कार्यालय जारी करता है। इस वर्ष के चरण पूछने के लिए लिखें या आएँ।",
        "adm_faq": "प्रवेश प्रश्नोत्तर",
        "adm_write": "कार्यालय को लिखें",
        "adm_write_p": "प्रवेश पूछताछ विद्यालय ईमेल पर जाती है।",
        "faq_q": "प्रश्न",
        "faq_q1": "आप कौन-सी कक्षाएँ पढ़ाते हैं?",
        "faq_a1": "सीडलिंग, सैपलिंग, एडवांस्ड सैपलिंग, और कक्षा १ से कक्षा ८ तक, धरहरा परिसर पर दिवसीय विद्यालय के रूप में।",
        "faq_q2": "आवेदन कैसे करूँ?",
        "faq_a2": "बच्चे का नाम, आयु या वांछित कक्षा और फोन नंबर के साथ npsd1970@gmail.com पर लिखें, या कार्यालय आएँ। शुल्क लेने वाला ऑनलाइन फॉर्म नहीं है।",
        "faq_q3": "क्या इस वेबसाइट पर शुल्क भर सकते हैं?",
        "faq_a3": "नहीं। शुल्क कार्यालय संभालता है और आधिकारिक नोट में दिया जाता है।",
        "faq_q4": "अंक और उपस्थिति कहाँ हैं?",
        "faq_a4": "परिणाम पृष्ठ खोलें और परीक्षा, कक्षा, अनुभाग, नाम तथा रोल से देखें। उपस्थिति कार्यालय के पास रहती है।",
        "faq_q5": "स्थानांतरण प्रमाणपत्र कैसे मिलेगा?",
        "faq_a5": "कार्यालय में आवेदन करें। इस वेबसाइट पर टीसी फॉर्म नहीं है।",
        "faq_q6": "शैक्षणिक कैलेंडर कहाँ है?",
        "faq_a6": "दर्शया गया वर्ष {year} है। अवकाश और बैठक की तिथियाँ परिपत्र से जाती हैं। सूचना बक्से खोलें, या कार्यालय से पूछें।",
        "faq_q7": "इस साइट पर चित्र कैसे उपयोग होते हैं?",
        "faq_a7": "गैलरी विद्यालय द्वारा जारी परिसर दृश्य दिखाती है। बच्चों के चित्र सार्वजनिक नाम-सूची के रूप में नहीं लगाए जाते।",
        "notices_from": "कार्यालय से",
        "notices_p": "परिपत्र — अवकाश, अभिभावक बैठकें, सत्र तिथियाँ — कक्षा-शिक्षकों तक जाते हैं, और माँगने पर ईमेल पर भी। पूरा पाठ या चित्र देखने के लिए सूचना खोलें। सूची में नाम लिखवाने के लिए npsd1970@gmail.com पर लिखें।",
        "gal_h": "परिसर के चित्र",
        "gal_p": "गैलरी धरहरा परिसर प्रस्तुत करती है — कक्षाएँ, मैदान और सभा स्थल। खंड खोलकर विद्यालय द्वारा जारी चित्र देखें। चित्र के नीचे बच्चों के नाम नहीं छपते।",
        "gal_1": "कक्षाएँ",
        "gal_2": "खेल मैदान",
        "gal_3": "सभा",
        "gal_4": "परिसर",
        "gal_5": "गतिविधियाँ",
        "gal_6": "कार्यालय",
        "gal_empty": "इस एल्बम की तस्वीरें यहाँ दिखेंगी।",
        "gal_all": "सभी एल्बम",
        "reach_place": "स्थान",
        "reach_p": "नूतन पब्लिक स्कूल वैशाली जिले के धरहरा में है। बच्चे दिन के लिए आते हैं और घर लौटते हैं। हाजीपुर, मुजफ्फरपुर या आस-पास के गाँव से आ रहे हों तो पहले लिखें, ताकि कार्यालय बता सके कब कोई आपका स्वागत करेगा।",
        "reach_follow": "लिखें या अनुसरण करें",
        "rules_in": "विद्यालय में",
        "rules_in_p": "बच्चों से अपेक्षा है कि वे उपस्थित रहें, दिन के लिए तैयार आएँ, शिष्टाचार से बोलें और दिया गया कार्य पूरा करें। सभा विद्यालय दिवस का भाग है। कक्षा में हिंदी और अंग्रेज़ी दोनों प्रयुक्त होते हैं।",
        "rules_circ": "परिपत्र",
        "rules_circ_p": "अवकाश, बैठकें और दिनचर्या में परिवर्तन परिपत्र से जाते हैं: इस वेबसाइट पर, कक्षा-शिक्षक के माध्यम से, और ईमेल सूची पर (npsd1970@gmail.com)। फेसबुक और इंस्टाग्राम पर कार्यालय जो संदेश चुनता है वे आते हैं। कार्यालय का कागज या ईमेल ही मान्य सूचना है।",
        "rules_visit": "मुलाकात",
        "rules_visit_p": "आने से पहले कार्यालय को लिखें या कॉल करें ताकि कोई आपका स्वागत कर सके। मुलाकात समय चालू वर्ष के लिए कार्यालय पुष्टि करता है।",
        "rules_priv": "गोपनीयता",
        "rules_priv_p": "छात्र सूची इन पृष्ठों पर प्रकाशित नहीं होती। गैलरी विद्यालय द्वारा जारी परिसर दृश्यों के लिए है। यहाँ का आचरण सार्वजनिक सार है; कार्यालय वर्ष के लिए मुद्रित नोट जोड़ सकता है।",
        "contact_school": "विद्यालय",
        "contact_school_name": "नूतन पब्लिक स्कूल, धरहरा · Nootan Public School, Dharhara",
        "contact_place_l": "स्थान",
        "contact_email_l": "ईमेल",
        "contact_circ": "परिपत्र कैसे पहुँचते हैं",
        "contact_circ_p": "इस साइट पर सूचना बक्से खोलें, कक्षा-शिक्षक से पूछें, ईमेल सूची के लिए npsd1970@gmail.com पर लिखें, या विद्यालय के फेसबुक और इंस्टाग्राम का अनुसरण करें।",
        "contact_write": "इस पृष्ठ से लिखें",
        "contact_write_p": "विद्यालय पूछताछ फॉर्म जैसे ही प्रश्न यहाँ भरें। जमा करने पर उत्तर कार्यालय को जाते हैं। इस वेबसाइट पर कुछ संग्रहीत नहीं होता।",
        "form_student": "छात्र का पूरा नाम",
        "form_father": "पिता का नाम",
        "form_mother": "माता का नाम",
        "form_phone": "संपर्क संख्या",
        "form_email": "अभिभावक का ईमेल पता",
        "form_grade": "जिस कक्षा के लिए आवेदन कर रहे हैं",
        "form_inquiry": "पूछताछ का प्रकार",
        "form_choose": "चुनें…",
        "form_query": "अपनी पूछताछ विस्तार से लिखें",
        "form_submit": "जमा करें",
        "form_thanks": "धन्यवाद। कार्यालय को आपका संदेश मिल गया है।",
        "form_required_meaning": "अनिवार्य",
        "form_required_abbr": "अनिवार्य",
        "form_grade_pre": "प्री-नर्सरी",
        "form_grade_seedling": "सीडलिंग (नर्सरी)",
        "form_grade_sapling": "सैपलिंग (एलकेजी)",
        "form_grade_adv": "एडवांस सैपलिंग (यूकेजी)",
        "form_grade_1": "कक्षा १",
        "form_grade_2": "कक्षा २",
        "form_grade_3": "कक्षा ३",
        "form_grade_4": "कक्षा ४",
        "form_grade_5": "कक्षा ५",
        "form_grade_6": "कक्षा ६",
        "form_grade_7": "कक्षा ७",
        "form_grade_8": "कक्षा ८",
        "form_inq_adm": "प्रवेश प्रक्रिया",
        "form_inq_fee": "शुल्क विवरण",
        "form_inq_exam": "परीक्षा कार्यक्रम",
        "form_inq_other": "अन्य",
        "careers_intro": "विद्यालय उन विषयों के लिए शिक्षकों पर विचार करता है जो यहाँ पढ़ाए जाते हैं — भाषा, गणित, विज्ञान, सामाजिक अध्ययन, कंप्यूटर, कला और शारीरिक शिक्षा। नीचे आवेदन करें; जमा करने पर आवेदन कार्यालय को जाता है।",
        "careers_apply": "शिक्षण के लिए आवेदन",
        "careers_name": "पूरा नाम",
        "careers_address": "पता",
        "careers_age": "आयु",
        "careers_gender": "लिंग",
        "careers_qual": "उच्चतम शैक्षणिक योग्यता",
        "careers_workplace": "पिछला कार्यस्थल",
        "careers_salary": "अपेक्षित वेतन (मासिक)",
        "careers_subjects": "आप कौन से विषय पढ़ा सकते हैं",
        "careers_subject_other": "अन्य विषय (यदि कोई हो)",
        "careers_classes": "आप किन कक्षाओं को पढ़ाने के लिए योग्य हैं",
        "careers_sample": "नमूना पाठ योजना या शिक्षण वीडियो का लिंक",
        "careers_thanks": "धन्यवाद। कार्यालय को आपका आवेदन मिल गया है।",
        "form_gender_male": "पुरुष",
        "form_gender_female": "महिला",
        "form_gender_other": "अन्य",
        "form_qual_bed": "बैचलर ऑफ एजुकेशन (बी.एड.)",
        "form_qual_med": "मास्टर ऑफ एजुकेशन (एम.एड.)",
        "form_qual_pg": "स्नातकोत्तर (पी.जी.)",
        "form_qual_ug": "स्नातक (यू.जी.)",
        "form_qual_other": "अन्य",
        "form_sub_math": "गणित",
        "form_sub_sci": "विज्ञान",
        "form_sub_eng": "अंग्रेज़ी",
        "form_sub_hin": "हिंदी",
        "form_sub_sst": "सामाजिक अध्ययन",
        "form_sub_comp": "कंप्यूटर",
        "form_sub_art": "कला और शारीरिक शिक्षा",
        "form_sub_evs": "ईवीएस",
        "form_cls_pre": "प्री-प्राइमरी (नर्सरी–केजी)",
        "form_cls_pri": "प्राइमरी (१–५)",
        "form_cls_mid": "मिडिल स्कूल (६–८)",
        "crumb_apply": "शिक्षण आवेदन",
        "results_see": "अपना परिणाम देखें",
        "results_p1": "अंक विद्यालय के परिणाम ऐप में देखे जाते हैं। अभिभावक बच्चे का विवरण भरकर अंकतालिका खोलते हैं।",
        "results_p2": "आपको <strong>परीक्षा</strong> (प्रथम चरण, द्वितीय चरण, अर्धवार्षिक, तृतीय चरण या वार्षिक), <strong>कक्षा</strong>, <strong>अनुभाग</strong>, <strong>छात्र का नाम</strong> और <strong>रोल</strong> चाहिए।",
        "results_cta": "अपना परिणाम देखें",
        "results_p3": "यदि खोज मेल न खाए तो बच्चे का नाम और कक्षा लिखकर कार्यालय को {mail} पर लिखें।",
        "toppers": "टॉपर्स",
        "toppers_p": "प्रत्येक परीक्षा के बाद विद्यालय कक्षावार उत्कृष्टता का सम्मान करता है — एक चित्र और संक्षिप्त वचन, परिवार की सहमति से।",
        "topper_photo": "चित्र",
        "topper_said": "उनके शब्द",
        "class_seedling": "सीडलिंग",
        "class_sapling": "सैपलिंग",
        "class_adv": "एडवांस्ड सैपलिंग",
        "class_1": "कक्षा १",
        "class_2": "कक्षा २",
        "class_3": "कक्षा ३",
        "class_4": "कक्षा ४",
        "class_5": "कक्षा ५",
        "class_6": "कक्षा ६",
        "class_7": "कक्षा ७",
        "class_8": "कक्षा ८",
        "class_1_5": "कक्षा १–५",
        "class_6_8": "कक्षा ६–८",
        "subj_early": "अंग्रेज़ी, हिंदी, गणित, ईवीएस, कला",
        "subj_adv": "अंग्रेज़ी, हिंदी, गणित, ईवीएस, कंप्यूटर",
        "subj_15": "अंग्रेज़ी, हिंदी, गणित, ईवीएस, कला, कंप्यूटर",
        "subj_68": "अंग्रेज़ी, हिंदी, गणित, विज्ञान, सामाजिक अध्ययन, संस्कृत, कंप्यूटर",
        "mail_subject_adm": "प्रवेश पूछताछ — एनपीएस धरहरा",
        "mail_subject_form": "विद्यालय पूछताछ — नूतन पब्लिक स्कूल, धरहरा",
        "fb_name": "नूतन पब्लिक स्कूल",
        "title_home": "नूतन पब्लिक स्कूल, धरहरा",
        "title_about": "परिचय · नूतन पब्लिक स्कूल, धरहरा",
        "title_academics": "शिक्षा · नूतन पब्लिक स्कूल, धरहरा",
        "title_life": "विद्यालय जीवन · नूतन पब्लिक स्कूल, धरहरा",
        "title_facilities": "सुविधाएँ · नूतन पब्लिक स्कूल, धरहरा",
        "title_admissions": "प्रवेश · नूतन पब्लिक स्कूल, धरहरा",
        "title_results": "परिणाम · नूतन पब्लिक स्कूल, धरहरा",
        "title_faq": "प्रश्नोत्तर · नूतन पब्लिक स्कूल, धरहरा",
        "title_notices": "सूचनाएँ · नूतन पब्लिक स्कूल, धरहरा",
        "title_gallery": "गैलरी · नूतन पब्लिक स्कूल, धरहरा",
        "title_careers": "करियर · नूतन पब्लिक स्कूल, धरहरा",
        "title_reach": "कैसे पहुँचें · नूतन पब्लिक स्कूल, धरहरा",
        "title_rules": "नियम · नूतन पब्लिक स्कूल, धरहरा",
        "title_contact": "संपर्क · नूतन पब्लिक स्कूल, धरहरा",
        "og_about": "परिचय · एनपीएस धरहरा",
        "og_academics": "शिक्षा · एनपीएस धरहरा",
        "og_life": "विद्यालय जीवन · एनपीएस धरहरा",
        "og_facilities": "सुविधाएँ · एनपीएस धरहरा",
        "og_admissions": "प्रवेश · एनपीएस धरहरा",
        "og_results": "परिणाम · एनपीएस धरहरा",
        "og_faq": "प्रश्नोत्तर · एनपीएस धरहरा",
        "og_notices": "सूचनाएँ · एनपीएस धरहरा",
        "og_gallery": "गैलरी · एनपीएस धरहरा",
        "og_careers": "करियर · एनपीएस धरहरा",
        "og_reach": "कैसे पहुँचें · एनपीएस धरहरा",
        "og_rules": "नियम · एनपीएस धरहरा",
        "og_contact": "संपर्क · एनपीएस धरहरा",
        "og_notice_fallback": "कार्यालय परिपत्र, नूतन पब्लिक स्कूल, धरहरा।",
    },
}


def t(lang: str, key: str) -> str:
    year = academic_year(lang)
    return UI[lang][key].replace("{year}", f'<span data-session-year>{year}</span>')
